<div id="masthead-image">
        <!-- TMPL_IF NAME="opacsmallimage" -->
        <img alt="<!-- TMPL_VAR NAME="LibraryName" -->" src="<!-- TMPL_VAR NAME="opacsmallimage" -->" />
        <!-- TMPL_ELSE -->
			<img src="/opac-tmpl/<!-- TMPL_VAR name="theme" -->/images/koha-logo-blue.png" alt="logo Koha">

        <!-- /TMPL_IF -->
</div>
<div id="masthead">
        <!-- TMPL_VAR NAME="LibraryName" -->
</div>
