<P>
<B>Key</B><BR>

<TABLE BORDER="0" CELLSPACING="5" cellpadding=0>
<TR>
	<TD valign="top"><IMG SRC="/images/sm-book.gif" WIDTH="35" HEIGHT="35" BORDER="0" align="center" ALT="Book"></TD>
	<TD align="center" valign="top"><IMG SRC="/images/sm-lg-print.gif" WIDTH="35" HEIGHT="35" BORDER="0" align="center" ALT="Large Print Book"></TD>
	<TD align="center" valign="top"><IMG SRC="/images/sm-picture-book.gif" WIDTH="35" HEIGHT="35" BORDER="0" align="center" ALT="Picture Book"></TD>
<TD align="center" valign="top"><IMG SRC="/images/sm-tape.gif" WIDTH="40" HEIGHT="35" BORDER="0" align="center" ALT="Video"></TD>
<TD align="center" valign="top"><IMG SRC="/images/sm-disk.gif" WIDTH="35" HEIGHT="35" BORDER="0" align="center" ALT="CD"></TD>
	<TD align="center" valign="top"><IMG SRC="/images/sm-dvd.gif" WIDTH="40" HEIGHT="35" BORDER="0" align="center" ALT="DVD"></TD>	
	<TD align="center" valign="top"><IMG SRC="/images/sm-jigsaw.gif" WIDTH="40" HEIGHT="35" BORDER="0" align="center" ALT="Jigsaw"></TD>
</TR>
<TR>
	<TD align="center" valign="top"><span class="tiny">Book</span></TD>
	<TD align="center" valign="top"><span class="tiny">Large Print Book</span></TD>
	<TD align="center" valign="top"><span class="tiny">Picture Book</span></TD><TD align="center" valign="top"><span class="tiny">Video</span></TD>
	<TD align="center" valign="top"><span class="tiny">CD</span></TD><TD align="center" valign="top"><span class="tiny">DVD</span></TD>	
	<TD align="center" valign="top"><span class="tiny">Jigsaw</span></TD>
</TR>
</TABLE>