<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tr valign="top"><td width="5"><img src="<TMPL_VAR NAME='themelang'>/images/styles/nav-left-left.gif" width="5" height="63" border="0" alt="" /></td>
  <td width="133"><table border="0" cellpadding="0" cellspacing="0" width="133">
  <tr valign="top"><td colspan="3" background=""><img src="<TMPL_VAR NAME='themelang'>/images/styles/left-top.gif" width="133" height="39" border="0" alt="" /></td></tr>
  <tr valign="top"><td width="9"><img src="<TMPL_VAR NAME='themelang'>/images/styles/left-2ndrow.gif" width="9" height="13" border="0" alt="" /></td>
    <td width="124" colspan="2" class="navhead"><!--+Katipo+start name="leftheading" include="/includes/membership-left-nav.inc" lastmod="12 Jun, 2002 at 18:24:46"--><a href="/membership/">Members</a><!--+Katipo+end--></td></tr>
<!--+Katipo+start name="leftnav" include="/includes/membership-left-nav.inc"-->

 
  <tr><td colspan="3"><img src="<TMPL_VAR NAME='themelang'>/images/holder.gif" width="1" height="5" border="0" alt="" /></td></tr>
<tr><td colspan="3"><img src="<TMPL_VAR NAME='themelang'>/images/holder.gif" width="1" height="5" border="0" alt="" /></td></tr>
  <tr valign="top"><td></td><td><img src="<TMPL_VAR NAME='themelang'>/images/styles/nav-dot.gif" width="9" height="13" border="0" alt="" /></td>
    <td width="115" class="sidenav"><a href="/cgi-bin/koha/opac-user.pl">My Account</a></td></tr>
<tr><td colspan="3"><img src="<TMPL_VAR NAME='themelang'>/images/holder.gif" width="1" height="5" border="0" alt="" /></td></tr>
  <tr valign="top"><td></td><td><img src="<TMPL_VAR NAME='themelang'>/images/styles/nav-dot.gif" width="9" height="13" border="0" alt="" /></td>
    <td width="115" class="sidenav"><a href="/cgi-bin/koha/opac-readingrecord.pl">Reading Record</a></td></tr>
<tr><td colspan="3"><img src="<TMPL_VAR NAME='themelang'>/images/holder.gif" width="1" height="5" border="0" alt="" /></td></tr>
  <tr valign="top"><td></td><td><img src="<TMPL_VAR NAME='themelang'>/images/styles/nav-dot.gif" width="9" height="13" border="0" alt="" /></td>
    <td width="115" class="sidenav"><a href="/cgi-bin/koha/opac-userdetails.pl">Personal Details</a></td></tr>
 
<!--+Katipo+end-->
  <tr><td colspan="3"><img src="<TMPL_VAR NAME='themelang'>/images/holder.gif" width="1" height="10" border="0" alt="" /></td></tr>
  </table>