<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tr valign="top"><td width="5"><img src="<TMPL_VAR NAME='themelang'>/images/styles/nav-left-left.gif" width="5" height="63" border="0" alt="" /></td>
  <td width="133"><table border="0" cellpadding="0" cellspacing="0" width="133">
  <tr valign="top"><td colspan="3" background=""><img src="<TMPL_VAR NAME='themelang'>/images/styles/left-top.gif" width="133" height="39" border="0" alt="" /></td></tr>
  <tr valign="top"><td width="9"><img src="<TMPL_VAR NAME='themelang'>/images/styles/left-2ndrow.gif" width="9" height="13" border="0" alt="" /></td>
    <td width="124" colspan="2" class="navhead"><!--+Katipo+start name="leftheading" include="/includes/search-left-nav.inc" lastmod="12 Jun, 2002 at 18:25:21"-->Searching<!--+Katipo+end--></td></tr>

<tr valign="top"><td></td><td width="9"><img height="13" alt="" src="<TMPL_VAR NAME='themelang'>/images/styles/nav-dot.gif" border="0" width="9" /></td><td class="sidenav" width="115"><!--+Katipo+start name="search" include="/includes/search-left-nav.inc"  lastmod="20 Oct, 2002 at 16:38:15"--><a href="/cgi-bin/koha/opac-search.pl">Search the Catalogue</a><!--+Katipo+end--></td></tr>

<tr><td colspan="3"><img height="5" alt="" src="<TMPL_VAR NAME='themelang'>/images/holder.gif" border="0" width="1" /></td></tr>    <tr valign="top"><td></td><td><img height="13" alt="" src="<TMPL_VAR NAME='themelang'>/images/styles/nav-dot.gif" border="0" width="9" /></td>      <td class="sidenav" width="115"><!--+Katipo+start name="historical" include="/includes/search-left-nav.inc" --><a href="http://horowhenuahistory.library.org.nz/">Horowhenua Historical Database</a><!--+Katipo+end--></td></tr>
 
 <tr><td colspan="3"><img height="5" alt="" src="<TMPL_VAR NAME='themelang'>/images/holder.gif" border="0" width="1" /></td></tr>    <tr valign="top"><td></td><td><img height="13" alt="" src="<TMPL_VAR NAME='themelang'>/images/styles/nav-dot.gif" border="0" width="9" /></td>      <td class="sidenav" width="115"><!--+Katipo+start name="internet" include="/includes/search-left-nav.inc" --><a href="/search/internet/">Search the Internet</a><!--+Katipo+end--></td></tr>

 <tr><td colspan="3"><img height="5" alt="" src="<TMPL_VAR NAME='themelang'>/images/holder.gif" border="0" width="1" /></td></tr>    <tr valign="top"><td></td><td><img height="13" alt="" src="<TMPL_VAR NAME='themelang'>/images/styles/nav-dot.gif" border="0" width="9" /></td>      <td class="sidenav" width="115"><!--+Katipo+start name="tutorial" include="/includes/search-left-nav.inc" --><a href="/search/internet/search-help.html">Search Tutorial</a><!--+Katipo+end--></td></tr>
  <tr><td colspan="3"><img src="<TMPL_VAR NAME='themelang'>/images/holder.gif" width="1" height="10" border="0" alt="" /></td></tr>
  </table>