<table border="0" width="100%" cellpadding="0" cellspacing="0">
<tr valign="top"><td width="10"><img src="<TMPL_VAR NAME='themelang'>/images/holder.gif" width="10" height="1" border="0" alt="" /></td>
  <td width="133"><a href="/cgi-bin/koha/opac-main.pl" class="button"><img src="<TMPL_VAR NAME='themelang'>/images/styles/hlt-logo.gif" width="133" height="33" border="0" alt="Horowhenua Library Trust" /></a></td>
  <td rowspan="2" background="<TMPL_VAR NAME='themelang'>/images/styles/search-pic.jpg"><table border="0" cellpadding="0" cellspacing="0">