<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tr valign="top"><td width="5"><img src="/images/styles/nav-left-left.gif" width="5" height="63" border="0" alt="" /></td>
  <td width="133"><table border="0" cellpadding="0" cellspacing="0" width="133">
  <tr valign="top"><td colspan="3" background=""><img src="/images/styles/left-top.gif" width="133" height="39" border="0" alt="" /></td></tr>
  <tr valign="top"><td width="9"><img src="/images/styles/left-2ndrow.gif" width="9" height="13" border="0" alt="" /></td>
    <td width="124" colspan="2" class="navhead"><!--+Katipo+start name="leftheading" include="/includes/teens-zone-left-nav.inc"--><a href="/teens-zone/">Teens Zone</a><!--+Katipo+end--></td></tr>
<!--+Katipo+start name="leftnav" include="/includes/teens-zone-left-nav.inc"--><tr valign="top"><td></td>
    <td width="9"><img src="/images/styles/nav-dot.gif" width="9" height="13" border="0" alt="" /></td>
    <td width="115" class="sidenav"><a href="/teens-zone/">main link</a></td></tr>
  <tr valign="top"><td></td><td class="sidenav" align="center">-</td>
    <td width="115" class="sidenav"><a href="/teens-zone/">secondary link</a></td></tr>
  <tr><td colspan="3"><img src="/images/holder.gif" width="1" height="5" border="0" alt="" /></td></tr>
  <tr valign="top"><td></td><td><img src="/images/styles/nav-dot.gif" width="9" height="13" border="0" alt="" /></td>
    <td width="115" class="sidenav"><a href="/teens-zone/">main link</a></td></tr>
  <tr valign="top"><td></td><td class="sidenav" align="center">-</td>
    <td width="115" class="sidenav"><a href="/teens-zone/">secondary link</a></td></tr><!--+Katipo+end-->
  <tr><td colspan="3"><img src="/images/holder.gif" width="1" height="10" border="0" alt="" /></td></tr>
  </table>