#!/bin/sh
#
# Find Koha source files that are not in UTF-8. Non-textual files are ignored.
# This script requires the isutf8 program from Joey Hess's moreutils package.
# See <http://kitenet.net/~joey/code/moreutils/> for info.
# 
# Copyright 2010 Catalyst IT Ltd
#
# This file is part of Koha.
#
# Koha is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Koha is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Koha; if not, see <http://www.gnu.org/licenses>.

set -e

git ls-files |
grep -Ev '\.(gif|jpg|png|pdf|ogg|psd|swf|odt|zip|ico|DS_Store|chr|dat)$' |
grep -v /js/tinymce/ |
while read filename
do
    if ! isutf8 -q "$filename" 
    then
        echo "$filename"
    fi
done

