#!/bin/sh
#
# Script to find files that probably should not be executed.
#
# Copyright 2010 Catalyst IT Ltd
#
# This file is part of Koha.
#
# Koha is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Koha is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Koha; if not, see <http://www.gnu.org/licenses>.

set -e

find . \
    -name misc -prune \
    -o -name svc -prune \
    -o -name xt -prune \
    -o -name t -prune \
    -o -name .git -prune \
    -o -name blib -prune \
    -o -name scripts -prune \
    -o -name debian -prune \
    -o -executable -type f \
        '!' -name '*.pl' \
        '!' -name '*.sh' \
        '!' -name '*.plugin' \
        '!' -name unapi \
        -print
