<!--
 list of Classes to be included in /catalogue/index.html and cat/index.html
 This is a qick-fix - These should really be fetched from the database
-->
<option value="E">Easy / Picture Books
<option value="ER">Easy Reader	
<option value="JNF">Junior Non-Fiction
<option value="JF">Junior Fiction
<option value="TREF">教師用書
<option value="FYA">Young Adult Fiction	
<option value="REF">參考書
<option value="F">小說類
<option value="NF">非小說類
<option value="CD">雷射唱片
<!--	<option value="E|ER">Easy Books-->

