<!--
 list of Classes to be included in /catalogue/index.html and cat/index.html
 This is a qick-fix - These should really be fetched from the database
-->
<option value="E">淺易/圖畫書
<option value="ER">淺易讀本	
<option value="JNF">兒童非小說類
<option value="JF">兒童小說類
<option value="TREF">教師參考書
<option value="FYA">青年小說類	
<option value="REF">參考書
<option value="F">小說
<option value="NF">非小說
<option value="CD">光碟
<!--	<option value="E|ER">Easy Books-->

