<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<!--Authored by rachel@katipo.co.nz 10:46 24/12/99-->

<html>
<head>
<title>KOHA: OPAC Catalogue Search</title>
<meta http-equiv="Content-Type" content="text/html; charset=big5">

</head>
<body text="black" bgcolor="white" link="#0000ff" vlink="#3366cc" Alink="#cc3300"
marginheight=0 marginwidth=0 leftmargin=0 topmargin=0 >



<!--HDL Colours

        Yellow = ffcc00 
        light blue = ccccff
        bright blue links = 0000ff
        aubergine = 663266 
        light green/grey = cccc99


-->

<!------------------------MENUS-------------------------------->

<table cellpadding=0 cellspacing=0 width="100%" border=0>
<tr BGCOLOR="#339999" >

        <td valign=bottom><img src="<TMPL_VAR NAME='themelang'>/images/inside-top-member.gif" 
	width=353 height=50 alt="KOHA: 讀者天地" hspace=0 vspace=0 border=0></td>

        <td align=right><a href="/cgi-bin/koha/opac-search.pl" 		onMouseOver="document.mouseover.src='<TMPL_VAR NAME='themelang'>/images/mouseover-search.gif'" 		onMouseOut="document.mouseover.src='/images/holder.gif'"><img 
	src="<TMPL_VAR NAME='themelang'>/images/menu-search.gif" 
	width=71 height=30 alt="查詢" hspace=0 vspace=0 border=0 name="menu-search"></a>
	
	<a href="/join.html"
	onMouseOver="document.mouseover.src='<TMPL_VAR NAME='themelang'>/images/mouseover-join.gif'" 		onMouseOut="document.mouseover.src='<TMPL_VAR NAME='themelang'>/images/holder.gif'"><img src="<TMPL_VAR NAME='themelang'>/images/menu-join.gif" 
	width=54 height=30 alt="登記" hspace=0 vspace=0 border=0 name="menu-join"></a>

	<a href="/cgi-bin/koha/opac-main.pl" 
	onMouseOver="document.mouseover.src='<TMPL_VAR NAME='themelang'>/images/mouseover-home.gif'" 		onMouseOut="document.mouseover.src='<TMPL_VAR NAME='themelang'>/images/holder.gif'"><img src="<TMPL_VAR NAME='themelang'>/images/menu-home.gif" 
	width=60 height=30 alt="主頁" hspace=0 vspace=0 border=0 name="menu-home"></a></td>
        
        </TR>


<tr valign=top>

        <td><img src="<TMPL_VAR NAME='themelang'>/images/inside-koha-bottom.gif" 
	width=69 height=44 alt="KOHA" hspace=0 vspace=0 border=0 ></td>

        <td align=right><img src="<TMPL_VAR NAME='themelang'>/images/holder.gif" 
	width=300 height=48 alt="" hspace=0 vspace=0 name="mouseover" ></a></td>

        </TR>



</TABLE>



<!-------------------------MAIN BODY OF PAGE-------------------------->
<BLOCKQUOTE>
