<!doctype html public "-//w3c//dtd html 4.0 transitional//en">

<html>
<head>
<title>KOHA: OPAC Catalogue Search</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso8859-1">

</head>
<body text="black" bgcolor="white" link="#0000ff" vlink="#3366cc" Alink="#cc3300"
marginheight=0 marginwidth=0 leftmargin=0 topmargin=0 >

<!--HDL Colours

        Yellow = ffcc00
        light blue = ccccff
        bright blue links = 0000ff
        aubergine = 663266
        light green/grey = cccc99


-->
<style>
a.white {
	font-weight: normal;
	text-decoration: none;
	cursor: hand;
	color:#FFFFFF;
	padding:4px;
	font-weight: bold;
	}
</style>
<!------------------------MENUS-------------------------------->

<table cellpadding=0 cellspacing=0 width="100%" border=0>
<tr BGCOLOR="#339999" >

	<td width="7%">
		<img src="<!-- TMPL_VAR name="themelang" -->/images/front-background-small.gif" height=50 align="center"><b>KOHA</b>
	</td>
        <td width="10%">
		<a href="/cgi-bin/koha/opac-search.pl" title="Search the catalogue" class="white">
			Search
		</a>
	</td>
        <td width="10%">
		<a href="/cgi-bin/koha/opac-user.pl" title="Join the library" class="white">
			Join
		</a>
	</td>
	<td align="left" width="10%">
		<a href="/cgi-bin/koha/opac-main.pl" title="home page" class="white">Home</a>
	</td>
	<td width="60%">
		&nbsp;
	</td>
        </TR>
</TABLE>

<!-------------------------MAIN BODY OF PAGE-------------------------->
<BLOCKQUOTE>
