#!/usr/bin/perl

# Copyright 2014 ByWater Solutions
#
# This file is part of Koha.
#
# Koha is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Koha is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Koha; if not, see <https://www.gnu.org/licenses>.
#

use Modern::Perl;

use CGI;
use JSON qw(to_json);

use C4::Auth qw(check_cookie_auth);

use Koha::Club::Enrollments;

my $cgi = CGI->new;

my ($auth_status) =
    check_cookie_auth( $cgi->cookie('CGISESSID'), { clubs => 'enroll' } );
if ( $auth_status ne "ok" ) {
    exit 0;
}

my $id = $cgi->param('id');

my $enrollment = Koha::Club::Enrollments->find($id);
$enrollment->cancel() if $enrollment;

binmode STDOUT, ':encoding(UTF-8)';
print $cgi->header( -type => 'application/json', -charset => 'UTF-8' );

print to_json( { success => $enrollment ? 1 : 0 } );
