<html><br clear=all>
<p> &nbsp; </p>


</BLOCKQUOTE>

<CENTER>
<FONT SIZE=2  face="arial, helvetica">
<A HREF="/cgi-bin/koha/mainpage.pl">Pocz±tek</a> ||
<A HREF="/cgi-bin/koha/loadmodules.pl?module=search&type=intranet">Katalog</a> ||
<A HREF="/cgi-bin/koha/members-home.pl">Cz³onkowie</a> ||
<A HREF="/cgi-bin/koha/loadmodules.pl?module=acquisitions">Akwizycje</a> ||
<A HREF="/cgi-bin/koha/circ/circulation.pl">Cyrkulacja</a> ||
<A HREF="/cgi-bin/koha/reports-home.pl">Reporty</a> ||
<A HREF="/cgi-bin/koha/admin-home.pl">Parametry</a> ||
<A HREF="/cgi-bin/koha/about.pl">About</a> || 
Pomoc
</FONT>
</CENTER>
</BODY>

</HTML>
