<br clear="all">
<p> &nbsp; </p>

<div class="center">
<a href="/cgi-bin/koha/mainpage.pl">Początek</a> ||
<a href="/cgi-bin/koha/loadmodules.pl?module=search&amp;type=intranet">Katalog</a> ||
<a href="/cgi-bin/koha/members/members-home.pl">Czytelnicy</a> ||
<a href="/cgi-bin/koha/loadmodules.pl?module=acquisitions">Gromadzenie</a> ||
<a href="/cgi-bin/koha/circ/circulation.pl">Cyrkulacja</a> ||
<a href="/cgi-bin/koha/reports-home.pl">Raporty</a> ||
<a href="/cgi-bin/koha/admin-home.pl">Parametry</a> ||
<a href="/cgi-bin/koha/about.pl">O nas</a> || 
Pomoc
</div>

</body>
</html>
