<br clear=all>
<p> &nbsp; </p>


</BLOCKQUOTE>

<CENTER>
<FONT SIZE=2  face="arial, helvetica">
<A HREF="/cgi-bin/koha/mainpage.pl">Początek</a> ||
<A HREF="/cgi-bin/koha/loadmodules.pl?module=search&type=intranet">Katalog</a> ||
<A HREF="/cgi-bin/koha/members-home.pl">Czytelnicy</a> ||
<A HREF="/cgi-bin/koha/loadmodules.pl?module=acquisitions">Gromadzenie</a> ||
<A HREF="/cgi-bin/koha/circ/circulation.pl">Cyrkulacja</a> ||
<A HREF="/cgi-bin/koha/reports-home.pl">Raporty</a> ||
<A HREF="/cgi-bin/koha/admin-home.pl">Parametry</a> ||
<A HREF="/cgi-bin/koha/about.pl">O nas</a> || 
Pomoc
</FONT>
</CENTER>
</BODY>

</HTML>
