TRUNCATE systempreferences;
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('template', 'default', 'Thème de présentation pour l\'interface bibliothécaire', NULL, 'Themes');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('autoBarcode', '0', 'Code barre auto-calculé', NULL, 'YesNo');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('acquisitions', 'normal', 'Acquisitions basé sur une gestion budgétaire (Normal) ou très simple, saisie directe dans le catalogue (simple)', 'simple|normal', 'Choice');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('autoMemberNum', '0', 'Le code lecteur est automatiquement calculé', NULL, 'YesNo');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('authoritysep', '--', 'Séparateur pour le thésaurus. Habituellement --', '10', 'free');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('opaclanguages', 'fr', 'Langage des interfaces bibliothécaire et OPAC', NULL, 'Languages');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('opacthemes', 'css', 'Thème de présentation de Koha', NULL, 'Themes');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('timeout', '120000000', 'Délai d\'inactivité avant de déconnexion automatique (en secondes)', NULL, 'Integer');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('marc', 'ON', 'Gestion MARC (ON ou OFF)', NULL, 'YesNo');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('marcflavour', 'UNIMARC', 'L\'encodage des caractères (MARC21 ou UNIMARC)', 'MARC21|UNIMARC', 'Choice');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('checkdigit', 'none', 'Vérification de validité sur la carte lecteur \'none\' pour aucun, \'Katipo\' pour la vérification comme chez Katipo', 'none|katipo', 'Choice');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('dateformat', 'metric', 'date format (US MM/JJ/AAA, métrique JJ/MM/AAAA, ISO AAAA/MM/JJ)', 'metric|us|iso', 'Choice');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('insecure', 'no', 'Si positionné à YES, AUCUNE authentification n\'est nécessaire puor utiliser Koha. Réfléchissez 2 fois avatn de mettre YES !', NULL, 'YesNo');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('maxoutstanding', '5', 'Dettes maximales pour être autorisé à faire des réservations', NULL, 'Integer');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('maxreserves', '5', 'Nombre maximum de réservations possibles pour un lecteur', NULL, 'Integer');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('noissuescharge', '5', 'Dettes maximales pour être autorisé à faire un emprunt', NULL, 'Integer');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('KohaAdminEmailAddress', 'your.mail@here', 'L\'adresse apparaissant sur les courriers électroniques envoyés', NULL, 'free');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('gist', '0.196', 'taux de TVA. Pas en %, mais sous forme numérique (0,055 pour 5,5%)', NULL, 'free');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('LibraryName', '<b>Bienvenue dans Koha</b>', 'Le nom de la bibliothèque tel qu\'il apparait dans l\'OPAC', NULL, '');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('ldapserver', '', 'Le nom du serveur LDAP', NULL, 'free');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('ldapinfos', '', 'Info ldap. Sera utilisé dans dn : uid=xxx, <ldapinfos>', NULL, 'free');