<!-- saas@users.sf.net 21-APR-2002 renamed "aquisitions" to "acquisitions" -->

<br clear=all>
<p> &nbsp; </p>

</BLOCKQUOTE>

<table cellpadding=0 cellspacing=0 width="100%" border=0>
<TR VALIGN=TOP BGCOLOR="000000"><TD  COLSPAN=6><img src="/images/blackdot.gif"  WIDTH=1  HEIGHT=2  HSPACE=0 vspace=0></TD></TR></TABLE>

<CENTER>
<FONT SIZE=2  face="arial, helvetica">
<A HREF="/">Home</a> ||
<A HREF="/cgi-bin/koha/circ/circulation.pl">Circulation</a> ||
<A HREF="/catalogue/">Catalogue</a> ||
<A HREF="/members/">Members</a> ||
<A HREF="/cgi-bin/koha/loadmodules.pl?module=acquisitions">Acquisitions</a> ||
<A HREF="/reports/">Reports</a> ||
<A HREF="/help/">Help</a> ||
<A HREF="http://opac.katipo.co.nz">OPAC</a> ||
<A HREF="http://www.library.org.nz">Library Website</a>
</FONT>
</CENTER>
</BODY>

</HTML>

