<br clear="all">
<p> &nbsp; </p>

<div class="center">
<a href="/cgi-bin/koha/mainpage.pl">Home</a> ||
<a href="/cgi-bin/koha/loadmodules.pl?module=search&type=intranet">Catalogue</a> ||
<a href="/cgi-bin/koha/members/members-home.pl">Members</a> ||
<a href="/cgi-bin/koha/loadmodules.pl?module=acquisitions">Acquisitions</a> ||
<a href="/cgi-bin/koha/circ/circulation.pl">Circulation</a> ||
<a href="/cgi-bin/koha/authorities/authorities-home.pl">Authorities</a> ||
<a href="/cgi-bin/koha/reports-home.pl">Reports</a> ||
<a href="/cgi-bin/koha/admin-home.pl">Parameters</a> ||
<a href="/cgi-bin/koha/about.pl">About</a> || 
Help
</div>

</body>
</html>
