<script type="text/javascript">
    var GB_ROOT_DIR = "[% interface %]/[% theme %]/lib/greybox/";
</script>
<script type="text/javascript" src="[% interface %]/[% theme %]/lib/greybox/AJS_[% KOHA_VERSION %].js"></script>
<script type="text/javascript" src="[% interface %]/[% theme %]/lib/greybox/AJS_fx_[% KOHA_VERSION %].js"></script>
<script type="text/javascript" src="[% interface %]/[% theme %]/lib/greybox/gb_scripts_[% KOHA_VERSION %].js"></script>
<link href="[% interface %]/[% theme %]/lib/greybox/gb_styles_[% KOHA_VERSION %].css" rel="stylesheet" type="text/css" />
