<div id="overdrive-login" class="modal hide" tabindex="-1" role="dialog" aria-labelledby="overdrive-login-label" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="closebtn" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="overdrive-login-label">Login</h3>
    </div>
    <form action="#" method="post" id="overdrive-login-form">
        <div class="modal-body">
                <fieldset class="brief">
                    <label for="ODpassword">Password:</label>
                    <input type="password" name="ODpassword" value="" />
                </fieldset>
        </div>
        <div class="modal-footer">
            <input type="submit" class="btn btn-primary overdrive-checkout-submit" value="Login" />
            <a href="#" data-dismiss="modal" aria-hidden="true" class="cancel">Cancel</a>
        </div>
    </form> <!-- /#overdrive-login-form -->
</div>  <!-- /#overdrive-login  -->
