<div id="overdrive-checkout" class="modal hide" tabindex="-1" role="dialog" aria-labelledby="overdrive-checkout-label" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="closebtn" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="overdrive-checkout-label">Checkout</h3>
    </div>
    <form action="#" method="post" id="overdrive-checkout-form">
        <div class="modal-body">
                <input type="hidden" name="id" value="" />
                <fieldset class="brief">
                    <label for="format">Format:</label>
                    <ul class="overdrive-format-list">
                </fieldset>
        </div>
        <div class="modal-footer">
            <input type="submit" class="btn btn-primary overdrive-checkout-submit" value="Checkout" />
            <a href="#" data-dismiss="modal" aria-hidden="true" class="cancel">Cancel</a>
        </div>
    </form> <!-- /#overdrive-checkout-form -->
</div>  <!-- /#overdrive-checkout  -->
