<div id="overdrive-login" class="modal" tabindex="-1" role="dialog" aria-labelledby="overdrive-login-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 id="overdrive-login-label" class="modal-title">Login</h3>
                <button type="button" class="closebtn" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="#" method="post" id="overdrive-login-form">
                <div class="modal-body">
                        <fieldset class="brief">
                            <label for="ODpassword">Password:</label>
                            <input type="password" name="ODpassword" id="ODpassword" value="" autocomplete="off" />
                        </fieldset>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary overdrive-checkout-submit" value="Login" />
                    <a href="#" data-dismiss="modal" aria-hidden="true" class="cancel">Cancel</a>
                </div>
            </form> <!-- /#overdrive-login-form -->
        </div> <!-- /.modal-content -->
    </div> <!-- /.modal-dialog -->
</div>  <!-- /#overdrive-login  -->
