<div id="recordedbooks-checkout" class="modal hide" tabindex="-1" role="dialog" aria-labelledby="recordedbooks-checkout-label" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="closebtn" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="recordedbooks-checkout-label">Checkout</h3>
    </div>
    <form action="#" method="post" id="recordedbooks-checkout-form">
        <div class="modal-body">
                <input type="hidden" name="id" value="" />
        </div>
        <div class="modal-footer">
            <input type="submit" class="btn btn-primary recordedbooks-checkout-submit" value="Checkout" />
            <a href="#" data-dismiss="modal" aria-hidden="true" class="cancel">Cancel</a>
        </div>
    </form> <!-- /#recordedbooks-checkout-form -->
</div>  <!-- /#recordedbooks-checkout  -->
