<!-- Checkout renewals modal -->
<div id="checkoutRenewals" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="checkoutRenewalsLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="closebtn" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="checkoutRenewalsLabel"> Item renewals</h3>
            </div> <!-- /.modal-header -->
            <div class="modal-body">
                <div id="retrieving" class="alert" style="display:none">Retrieving renewals...</div>
                <div id="incomplete" class="alert" style="display:none"></div>
                <ul id="results" style="display:none"></ul>
            </div> <!-- /.modal-body -->
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
            </div> <!-- /.modal-footer -->
        </div> <!-- /.modal-content -->
    </div> <!-- /.modal-dialog -->
</div> <!-- /#checkoutRenewals -->
