<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Cestino OPAC</title>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
	<link rel="stylesheet" type="text/css" href="<!-- TMPL_VAR name="themelang">/includes/opac.css">
	<script type="text/javascript" language="javascript" src="<!-- TMPL_VAR NAME="themelang" -->/includes/basket.js"></script>
	<script language="JavaScript" type="text/javascript">
		function _(s) { return s } // dummy function for gettext
		//
	</script>
	<SCRIPT language='javascript'>
		var MSG_NO_RECORD_SELECTED = _("Nessuna scheda bibliografica selezionata");
		var MSG_NO_RECORD_ADDED = _("Nessuna scheda bibliografica aggiunta");
		var MSG_CONFIRM_DEL_BASKET = _("Vuoi svuotare il cestino?");
		var MSG_CONFIRM_DEL_RECORDS = _("Vuoi cancellare le schede selezionate?");
	</SCRIPT>
</head>
