</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="<!-- TMPL_VAR NAME='themelang' -->/includes/favicon.ico" type="image/x-icon" />
<style type="text/css"> 
	<!-- TMPL_IF NAME="intranetstylesheet" -->@import url(<!-- TMPL_VAR NAME='themelang' -->/includes/<!-- TMPL_VAR NAME="intranetstylesheet" -->);<!-- TMPL_ELSE -->@import url(<!-- TMPL_VAR NAME='themelang' -->/includes/intranet.css);<!-- /TMPL_IF -->
	<!-- TMPL_IF NAME="intranetcolorstylesheet" -->@import url(<!-- TMPL_VAR NAME='themelang' -->/includes/<!-- TMPL_VAR NAME="intranetcolorstylesheet" -->);<!-- /TMPL_IF -->
</style>
<!-- TMPL_INCLUDE NAME="common.js.inc" -->
<script language="JavaScript" type="text/javascript">
<!-- Hide from old browsers

	function CheckAll() {
		count = document.mainform.elements.length;
	    for (i=0; i < count; i++) {
		    if(document.mainform.elements[i].checked == 1){
				document.mainform.elements[i].checked = 0;
			} else {
				document.mainform.elements[i].checked = 1;
			}
		}
	}
 
// end hiding -->
</script>
</head>

<body>
