<div id="nav">
<ul>
				<li><h4>Koha</h4></li>

				<li><a href="/cgi-bin/koha/mainpage.pl">Koha intranet home</a></li>
				<li><a href="/cgi-bin/koha/circ/circulation.pl">Circulation</a><ul><li><a href="/cgi-bin/koha/circ/circulation.pl">Issues</a>	</li><li><a href="/cgi-bin/koha/circ/returns.pl">Returns</a></li><li><a href="/cgi-bin/koha/circ/branchtransfers.pl">Transfers</a></li></ul></li>
				<li><a href="/cgi-bin/koha/members-home.pl">Patrons</a></li>
				<li><a href="/cgi-bin/koha/loadmodules.pl?module=search&amp;marc=0&amp;type=intranet">Catalog</a><ul><li><a href="/cgi-bin/koha/loadmodules.pl?module=search&amp;marc=0&amp;type=intranet">Advanced Search</a></li>
<li><a href="/cgi-bin/koha/loadmodules.pl?module=search&amp;marc=1&amp;type=intranet">MARC Search</a></li>
</ul></li>
<li><a href="/cgi-bin/koha/acqui.simple/addbooks.pl">Cataloging</a><ul><li><a href="/cgi-bin/koha/acqui.simple/addbiblio.pl">Add MARC</a></li></ul></li>
			</ul>
</div>