<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Koha Intranet</title>
<!-- TMPL_IF NAME="TemplateEncoding" -->
<meta http-equiv="Content-Type" content="text/html; charset=<!-- TMPL_VAR NAME='TemplateEncoding' -->" />
<!-- TMPL_ELSE -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- /TMPL_IF -->
<link rel="shortcut icon" href="<!-- TMPL_VAR NAME='themelang' -->/includes/favicon.ico" type="image/x-icon" />
<style type="text/css"> 
	@import url(<!-- TMPL_VAR NAME='themelang' -->/includes/print.css);
</style>
</head>

<body>
