<div id="topmenu"><a href="/cgi-bin/koha/members-home.pl">Patrons Home</a> | <form action="/cgi-bin/koha/member.pl" method="post">
<label for="member">Patron Search</label>
  <input type="text" id="member" name="member" value="" />&nbsp;<input type="submit"  class="submit" name="Go" value="Search" /></form><form action="/cgi-bin/koha/simpleredirect.pl" method="post">
<input type="submit" class="submit" value="Add New Patron" />
<input type="hidden" name="chooseform" value="adult" />
</form></div>