<div id="mana_comment_progress" class="dialog message mana_comment_status" style="display:none">
    <div id="loading"> <img src="[% interface | html %]/[% theme | html %]/img/spinner-small.gif" alt="" /> Submitting comment </div>
</div>
<div id="mana_comment_success" class="dialog message mana_comment_status" style="display:none">
    Your comment has been submitted
</div>
<div id="mana_comment_failed" class="dialog alert mana_comment_status" style="display:none">
    Your comment could not be submitted. Please try again later.
</div>