<br clear="all">
<p> &nbsp; </p>

<div class="center">
<a href="/cgi-bin/koha/mainpage.pl">Inicio</a> ||
<a href="/cgi-bin/koha/loadmodules.pl?module=search&amp;type=intranet">Cat&aacute;logo</a> ||
<a href="/cgi-bin/koha/members/members-home.pl">Usuarios</a> ||
<a href="/cgi-bin/koha/loadmodules.pl?module=acquisitions">Adquisiciones</a> ||
<a href="/cgi-bin/koha/circ/circulation.pl">Circulaci&oacute;n</a> ||
<a href="/cgi-bin/koha/reports-home.pl">Informes</a> ||
<a href="/cgi-bin/koha/admin-home.pl">Par&aacute;metros</a> ||
<a href="/cgi-bin/koha/about.pl">Acerca de</a> || 
Ayuda
</div>

</body>
</html>
