<!--
 list of Classes to be included in /catalogue/index.html and cat/index.html
 This is a qick-fix - These should really be fetched from the database
-->
<option value="E">F&aacute;cil / Libros Ilustrados
<option value="ER">Lector F&aacute;cil	
<option value="JNF">Junior Non-Fiction
<option value="JF">Junior Fiction
<option value="TREF">Teacher Reference
<option value="FYA">J&oacute;ven Adulto Ficci&oacute;n	
<option value="REF">Libros de Referencia
<option value="F">Ficci&oacute;n
<option value="NF">Non-Fiction
<option value="CD">Disco Compacto
<!--	<option value="E|ER">Easy Books-->

