<!--
 list of Classes to be included in /catalogue/index.html and cat/index.html
 This is a qick-fix - These should really be fetched from the database
-->
<option value="E">
F&aacute;cil / Libros con Dibujos<option value="ER">Lectua F&aacute;cil<option value="JNF">No-Ficci&oacute;n 
para J&oacute;venes<option value="JF"> Ficci&oacute;n para J&oacute;venes<option value="TREF">Referencia 
para Maestros<option value="FYA"> Ficci&oacute;n para Adultos j&oacute;venes<option value="REF">Libros 
de Referencia<option value="F"> Ficci&oacute;n<option value="NF"> No-Ficci&oacute;n <option value="CD"> 
Compact Disc 
<!--	<option value="E|ER">Easy Books-->
