<!--
 list of Classes to be included in /catalogue/index.html and cat/index.html
 This is a qick-fix - These should really be fetched from the database
-->
<option value="E">Fácil / Libros con Dibujos
<option value="ER">Lectura Fácil
<option value="JNF">Junior No-Ficción
<option value="JF">Junior Ficción
<option value="TREF">Referencia del Profesor
<option value="FYA">Ficción para Adultos
<option value="REF">Manuales de Referencia
<option value="F">Ficción
<option value="NF">No-Ficción
<option value="CD">Disco Compacto
<!--	<option value="E|ER">Easy Books-->

