<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<!--Authored by rachel@katipo.co.nz 104:38 1/11/99-->
<!--updated by rachel@katipo.co.nz 01:02 5/11/99-->

<html>
<head>
<title>KOHA: INTRANET: Entregas y Devoluciones</title>

</head>
<body text="black" bgcolor="white" link="#0000ff" vlink="#0000ff" "3366cc" Alink="#cc3300"
marginheight=0 marginwidth=0 leftmargin=0 topmargin=0 >



<!--HDL Colours

	Yellow = ffcc00
	light blue = ccccff
	bright blue links = 0000ff
	aubergine = 663266
	light green/grey = cccc99


-->

<!------------------------MENUS-------------------------------->

<table cellpadding=0 cellspacing=0 width="100%" border=0>
<tr valign=top bgcolor=ffcc00  >

	<td COLSPAN=3>
	<table cellpadding=0 cellspacing=0  border=0 height=29>
	<tr valign=top bgcolor=ffcc00  >
	<td background="/images/issues-spot-1.gif" width="224"
	height="29"><font size=1 face="arial"><img src="/images/holder.gif" width=210 height=4 alt=" " hspace=0 vspace=0><br>
	<img src="/images/holder.gif"
	width=35 height=21 align=left alt=" " hspace=0 vspace=0>KOHA: <A HREF="/cgi-bin/koha/mainpage.pl">HDL INTRANET</A><br>
	<img src="/images/holder.gif" width=210 height=1 alt=" " hspace=0 vspace=0></FONT></td>

	</TR></TABLE></TD>

<TD COLSPAN=3 align=right><font size=1 face="arial" color="white">I 1 &nbsp; &nbsp; </font></TD>


</tr>


<TR VALIGN=TOP BGCOLOR="ffcc00"><TD  COLSPAN=6><img src="/images/holder.gif"  WIDTH=1  HEIGHT=12  HSPACE=0 vspace=0></TD></TR>
<tr valign=top bgcolor=ffcc00 >
<TD COLSPAN=4>&nbsp;</TD>
	<td  ALIGN=RIGHT COLSPAN=2 >
	<table cellpadding=0 cellspacing=0  border=0 height=29>

<tr valign=top bgcolor=ffcc00 >
	<td background="/images/issues-spot-2.gif" width="235"
	height="29"  ALIGN=RIGHT ><font size=1 face="arial"><img src="/images/holder.gif" width=223 height=12 alt=" " hspace=0 vspace=0><br>
	<img src="/images/holder.gif"
	width=26 height=17 align=right alt=" " hspace=0 vspace=0>Está en <A HREF="index.html">ENTREGAS Y DEVOLUCIONES</a><br>
	<img src="/images/holder.gif" width=223 height=1 alt=" " hspace=0 vspace=0></FONT></td>

	</TR></TABLE></TD>




</tr>
<TR VALIGN=TOP BGCOLOR="000000"><TD  COLSPAN=6><img src="/images/blackdot.gif"  WIDTH=1  HEIGHT=2  HSPACE=0 vspace=0></TD></TR>

</table>
<BLOCKQUOTE>
