<br clear=all>
<p>&nbsp;  </p>




<table cellpadding=0 cellspacing=0 width="100%" border=0>
<TR VALIGN=TOP BGCOLOR="000000"><TD  COLSPAN=6><img src="/images/blackdot.gif"  WIDTH=1  HEIGHT=2  HSPACE=0 vspace=0></TD></TR></TABLE>


<CENTER>
  <FONT SIZE=2  face="arial, helvetica"> <A HREF="/cgi-bin/koha/mainpage.pl">Home</a> 
  || <A HREF="/cgi-bin/koha/circ/circulation.pl">Circulaci&oacute;n</a> || <A HREF="/cgi-bin/koha/loadmodules.pl?module=search&type=intranet">Cat&aacute;logo</a> 
  || <A HREF="/cgi-bin/koha/members-home.pl">Usuarios</a> || <A HREF="/cgi-bin/koha/loadmodules.pl?module=acquisitions">Adquisiciones</a> 
  || <A HREF="/cgi-bin/koha/reports-home.pl">Informes</a> || <A HREF="/cgi-bin/koha/admin-home.pl">Par&aacute;metros 
  del Sistema</a> || <A HREF="/help/">Ayuda</a> </FONT> 
</CENTER>
</BODY>

</HTML>
