<ul id="navigation">
	<li>    <a href="/cgi-bin/koha/cataloguing/addbiblio.pl?biblionumber=[% biblionumber %]">Edit Bibliographic Record</a></li>
	<li>    <a href="/cgi-bin/koha/catalogue/detail.pl?biblionumber=[% biblionumber %]">Normal view</a></li>
	<li>    <a href="/cgi-bin/koha/catalogue/MARCdetail.pl?biblionumber=[% biblionumber %]">View MARC in Catalog</a></li>
	<li>    <a href="/cgi-bin/koha/catalogue/ISBDdetail.pl?biblionumber=[% biblionumber %]">View ISBD in Catalog</a></li>
</ul>