<br clear="all" />

<div class="center">
<a href="/cgi-bin/koha/mainpage.pl">Home</a> ||
<a href="/cgi-bin/koha/catalogue/search.pl">Catalog</a> ||
<a href="/cgi-bin/koha/members/members-home.pl">Members</a> ||
<a href="/cgi-bin/koha/acqui/acqui-home.pl">Acquisitions</a> ||
<a href="/cgi-bin/koha/circ/circulation.pl">Circulation</a> ||
<a href="/cgi-bin/koha/reports-home.pl">Reports</a> ||
<a href="/cgi-bin/koha/admin-home.pl">Parameters</a> ||
<a href="/cgi-bin/koha/about.pl">About Koha</a> || 
Help
</div>

</body>
</html>
