<script type="text/javascript">                            
    var GB_ROOT_DIR = "[% themelang %]/lib/greybox/";                               
</script>
<script type="text/javascript" src="[% themelang %]/lib/greybox/AJS.js"></script>
<script type="text/javascript" src="[% themelang %]/lib/greybox/AJS_fx.js"></script>
<script type="text/javascript" src="[% themelang %]/lib/greybox/gb_scripts.js"></script>
<link href="[% themelang %]/lib/greybox/gb_styles.css" rel="stylesheet" type="text/css" />
