<div id="navmenu"><ul id="navmenulist">
	<li><a href="/cgi-bin/koha/patroncards/home.pl">Patron Card Creator Home</a></li>
	<li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=layout">Manage Layouts</a></li>
	<li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=template">Manage Templates</a></li>
	<li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=profile">Manage Profiles</a></li>
	<li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=batch">Manage Batches</a></li>
	<li><a href="/cgi-bin/koha/patroncards/image-manage.pl">Manage Images</a></li>
</ul>
</div>
