<br clear="all">
<p> &nbsp; </p>

<div class="center">
<a href="/cgi-bin/koha/mainpage.pl">Start</a> ||
<a href="/cgi-bin/koha/loadmodules.pl?module=search&amp;type=intranet">Katalog</a> ||
<a href="/cgi-bin/koha/members/members-home.pl">Benutzer</a> ||
<a href="/cgi-bin/koha/loadmodules.pl?module=acquisitions">Erwerbung</a> ||
<a href="/cgi-bin/koha/circ/circulation.pl">Ausleihe</a> ||
<a href="/cgi-bin/koha/authorities/authorities-home.pl">Authorities</a> ||
<a href="/cgi-bin/koha/reports-home.pl">Reports</a> ||
<a href="/cgi-bin/koha/admin-home.pl">Parameter</a> ||
<a href="/cgi-bin/koha/about.pl">&Uuml;ber</a> || 
Hilfe
</div>

</body>
</html>
