<!--
 list of Classes to be included in /catalogue/index.html and cat/index.html
 This is a qick-fix - These should really be fetched from the database
-->
<option value="E">Easy / Picture Books
<option value="ER">Easy Reader	
<option value="JNF">SAchliteratur f&uuml;r Jugendliche
<option value="JF">Sch&ouml;ne Literatur f&uuml;r Jugendliche
<option value="TREF">Teacher Reference
<option value="FYA">Romane f&uuml; Jugendliche	
<option value="REF">Nachschlagebestand
<option value="F">Belletristik
<option value="NF">Sachliteratur
<option value="CD">CD
<!--	<option value="E|ER">Easy Books-->

