<!--
 list of Classes to be included in /catalogue/index.html and cat/index.html
 This is a qick-fix - These should really be fetched from the database
-->
<option value="E">Дитячі / мальовані книжечки
<option value="ER">Легкий читач	
<option value="JNF">Юнацька наукова література
<option value="JF">Юнацька белетристика
<option value="TREF">Довідник вчителя
<option value="FYA">Молодіжна белетристика	
<option value="REF">Довідники
<option value="F">Белетристика
<option value="NF">Наукова література
<option value="CD">Компакт-диск
<!--	<option value="E|ER">Easy Books-->

