<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>OPAC Basket</title>
	<link rel="stylesheet" type="text/css" href="<!-- TMPL_VAR name="themelang">/includes/opac.css">
	<script type="text/javascript" language="javascript" src="<!-- TMPL_VAR NAME="themelang" ESCAPE=URL -->/includes/basket.js"></script>
	<SCRIPT language='javascript'>
		var MSG_NO_RECORD_SELECTED = "No biblio selected";
		var MSG_NO_RECORD_ADDED = "No biblio added";
		var MSG_CONFIRM_DEL_BASKET = "Do you want to empty the basket ?"
		var MSG_CONFIRM_DEL_RECORDS = "Do you want to remove selected biblios ?";
	</SCRIPT>
</head>
