<TMPL_IF NAME="book">
<IMG SRC="<TMPL_VAR NAME='themelang'>/images/book.gif" WIDTH="50" HEIGHT="45" BORDER="0">
</TMPL_IF>
<TMPL_IF NAME="largeprint">
<IMG SRC="<TMPL_VAR NAME='themelang'>/images/large-print.gif" WIDTH="50" HEIGHT="45" BORDER="0">
</TMPL_IF>
<TMPL_IF NAME="picture">
<IMG SRC="<TMPL_VAR NAME='themelang'>/images/magazine.gif" WIDTH="50" HEIGHT="45" BORDER="0">
</TMPL_IF>
<TMPL_IF NAME="cdrom">
<IMG SRC="<TMPL_VAR NAME='themelang'>/images/disk.gif" WIDTH="50" HEIGHT="45" BORDER="0">
</TMPL_IF>
<TMPL_IF NAME="cassette">
<IMG SRC="<TMPL_VAR NAME='themelang'>/images/disk.gif" WIDTH="50" HEIGHT="45" BORDER="0">
</TMPL_IF>
<TMPL_IF NAME="cd">
<IMG SRC="<TMPL_VAR NAME='themelang'>/images/disk.gif" WIDTH="50" HEIGHT="45" BORDER="0">
</TMPL_IF>
<TMPL_IF NAME="video">
<IMG SRC="<TMPL_VAR NAME='themelang'>/images/tape.gif" WIDTH="50" HEIGHT="45" BORDER="0">
</TMPL_IF>
<TMPL_IF NAME="bag">
<IMG SRC="<TMPL_VAR NAME='themelang'>/images/book.gif" WIDTH="50" HEIGHT="45" BORDER="0">
</TMPL_IF>
<TMPL_IF NAME="magazine">
<IMG SRC="<TMPL_VAR NAME='themelang'>/images/magazine.gif" WIDTH="50" HEIGHT="45" BORDER="0">
</TMPL_IF>
<TMPL_IF NAME="puzzle">
<IMG SRC="<TMPL_VAR NAME='themelang'>/images/jigsaw.gif" WIDTH="50" HEIGHT="45" BORDER="0">
</TMPL_IF>
<TMPL_IF NAME="picturebook">
<IMG SRC="<TMPL_VAR NAME='themelang'>/images/picture-book.gif" WIDTH="50" HEIGHT="45" BORDER="0">
</TMPL_IF>
<TMPL_IF NAME="map">
<IMG SRC="<TMPL_VAR NAME='themelang'>/images/map.gif" WIDTH="50" HEIGHT="45" BORDER="0">
</TMPL_IF>
<TMPL_IF NAME="photograph">
<IMG SRC="<TMPL_VAR NAME='themelang'>/images/magazine.gif" WIDTH="50" HEIGHT="45" BORDER="0">
</TMPL_IF>
<TMPL_IF NAME="talkingbook">
<IMG SRC="<TMPL_VAR NAME='themelang'>/images/talking-book.gif" WIDTH="50" HEIGHT="45" BORDER="0">
</TMPL_IF>
<TMPL_IF NAME="dvd">
<IMG SRC="<TMPL_VAR NAME='themelang'>/images/dvd.gif" WIDTH="50" HEIGHT="45" BORDER="0">
</TMPL_IF>
