#!/usr/bin/perl

# Copyright 2011 Chris Cormack <chris@bigballofwax.co.nz>
#
# This file is part of Koha.
#
# Koha is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# Koha is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with Koha; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


use strict;
use warnings;

use C4::Reports::Guided;
use JSON;
use CGI;

use Koha::Cache;

my $query  = CGI->new();
my $report_id = $query->param('id');
my $report_name = $query->param('name');

my $cache;
my $sql;
my $type;
my $notes;
my $cache_expiry;
my $public;

( $sql, $type, $report_name, $notes, $cache_expiry, $public, $report_id ) =
  get_saved_report($report_name ? { 'name' => $report_name } : { 'id' => $report_id } );
die "Sorry this report is not public\n" unless $public;

if (Koha::Cache->is_cache_active) {
    $cache = Koha::Cache->new(
    );
    my $page = $cache->get_from_cache("opac:report:$report_id");
    if ($page) {
        print $query->header;
        print $page;
        exit;
    }
}

print $query->header;
if ($sql) {
    my $offset = 0;
    my $limit  = C4::Context->preference("SvcMaxReportRows") || 10;
    my ( $sth, $errors ) = execute_query( $sql, $offset, $limit );
    my $lines     = $sth->fetchall_arrayref;
    my $json_text = to_json($lines);
    print $json_text;

    if (Koha::Cache->is_cache_active) {
        $cache->set_in_cache( "opac:report:$report_id", $json_text, $cache_expiry );
    }
}
