<div id="topmenu"><form action="/cgi-bin/koha/member.pl" method="post">
<label for="member">Пошук відвідувача</label>
  <input type="text" id="member" name="member" value="" />&nbsp;<input type="submit" class="submit" name="Go" value="Пошук"></form><form action="/cgi-bin/koha/simpleredirect.pl" method="post">
<input type="submit" class="submit" value="Додати нового відвідувача">
<input type="hidden" name="chooseform" value="adult" />
</form></div>