<div id="topmenu"><a href="/cgi-bin/koha/members/members-home.pl">Домівка відвідувачів</a> | <form action="/cgi-bin/koha/members/member.pl" method="post">
<label for="member">Пошук відвідувача</label>
  <input type="text" id="member" name="member" value="" />&nbsp;<input type="submit" class="submit" name="Go" value="Пошук"></form><form action="/cgi-bin/koha/members/memberentry.pl" method="post">
<input type="submit" class="submit" value="Додати нового відвідувача">
<input type="hidden" name="actionType" value="Add" />
</form></div>