INSERT INTO biblio_framework VALUES ('CART','Documents cartographiques');
INSERT INTO marc_tag_structure VALUES ('711','collectivité - coauteur','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('001','numéro d\'identification de la notice','notice numéro',0,1,'','CART');
INSERT INTO marc_tag_structure VALUES ('005','numéro d\'identification de la version','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('100','données générales de traitement','',0,1,'','CART');
INSERT INTO marc_tag_structure VALUES ('101','langue du document','langue',0,1,'','CART');
INSERT INTO marc_tag_structure VALUES ('102','pays d\'édition ou de production','',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('122','zone de données codées : période historique','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('200','titre et mention de responsabilité','titre',0,1,'','CART');
INSERT INTO marc_tag_structure VALUES ('205','mention d\'édition','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('210','adresse bibliographique','éditeur',0,0,NULL,'CART');
INSERT INTO marc_tag_structure VALUES ('211','date de publication prévue','date de publication prévue',0,0,NULL,'CART');
INSERT INTO marc_tag_structure VALUES ('215','collation','description',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('225','collection','collection',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('300','note générale','note',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('302','note sur les informations codées','note',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('303','note générale sur la description bibliographique','note',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('304','note sur le titre et la mention de responsabilité','note',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('305','note sur l\'édition et l\'histoire bibliographique','note',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('306','note sur l\'adresse bibliographique','note',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('307','note sur la collation','note',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('308','note sur la collection','note',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('311','note sur les zones de liens','note',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('312','note sur les titres associés','note',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('313','note sur les vedettes matières','note',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('314','note sur la responsabilité intellectuelle','note',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('315','note sur les informations propres au type de documents','note',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('324','note sur le document original','note',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('325','note sur la reproduction','note',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('327','note de contenu','note',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('330','résumé ou extrait','résumé',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('332','titre choisi pour le document','forme du titre',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('333','note sur le public destinataire','destiné à',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('345','renseignements sur l\'acquisition','note',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('410','collection','collection',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('411','sous-collection','sous-collection',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('451','autre édition sur le même support','autre édition',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('452','autre édition sur un autre support','autre édition',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('453','traduit sous le titre','traduit sous le titre',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('454','traduit de','traduit de',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('455','reproduction de','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('456','reproduit comme','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('461','niveau de l\'ensemble','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('462','niveau du sous-ensemble','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('463','niveau de l\'unité matérielle','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('464','niveau du dépouillement','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('488','autres œuvres en liaison','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('510','titre parallèle','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('515','titre courant','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('517','autres variantes du titre','autres variantes du titre',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('540','titre ajouté par le catalogueur','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('541','titre traduit ajouté par le catalogueur','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('600','nom de personne - vedette matière','sujets',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('601','collectivité - vedette matière','sujets',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('602','nom générique de famille - vedette matière','sujets',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('604','auteur-titre - vedette matière','sujets',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('605','titre - vedette matière','sujets',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('606','nom commun - vedette matière','sujets',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('607','Nom geographique - vedette matiere','sujets',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('608','vedette matière de forme, de genre ou des caractéristiques physiques','sujets',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('610','indexation en vocabulaire libre','sujets',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('615','catégorie sujet','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('620','accès par le lieu d\'édition','lieu d\'édition',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('661','code de date','',0,1,NULL,'CART');
INSERT INTO marc_tag_structure VALUES ('676','classification décimale Dewey','classification',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('700','nom de personne - responsabilité principale','auteur',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('701','nom de personne - coauteur','coauteur',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('702','nom de personne - mention de responsabilité secondaire','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('710','collectivité - mention de responsabilité principale','auteur',0,0,NULL,'CART');
INSERT INTO marc_tag_structure VALUES ('712','collectivité - mention de responsabilité secondaire','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('720','nom générique de famille - mention de responsabilité principale','',0,0,NULL,'CART');
INSERT INTO marc_tag_structure VALUES ('721','nom générique de famille - coauteur','',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('722','nom générique de famille - mention de responsabilité secondaire','',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('801','source de catalogage','',1,1,'SOURCES','CART');
INSERT INTO marc_tag_structure VALUES ('830','Note generale du catalogueur','Note generale du catalogueur',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('120','Zone de donnees codees : documents cartographiques, generalites','',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('121','Zone de donnees codees : Documents cartographiques, caracteristiques physiques','',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('123','zone de donnees codees : documents cartographiques, echelle et coordonnees','',1,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('124','zone de donnees codees : documents cartographiques, autres caracteristiques physiques','',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('131','zone de donnees codees : documents cartographiques - mesures geodesiques','',0,0,'','CART');
INSERT INTO marc_tag_structure VALUES ('206','zone particuliere a certains types de documents : documents cartographiques, donnees mathematiques','',1,0,'','CART');
INSERT INTO marc_subfield_structure VALUES ('123','c','Echelle horizontale a taux lineaire constant (echelle altimetrique)','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('123','a','type d\'echelle','',0,0,'',1,'','','unimarc_field_123a.pl',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('123','b','Echelle horizontale a taux lineaire constant','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('123','@','Epoque','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('123','0','Epoque','',0,0,'',1,'','',NULL,0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('121','b','photographie aerienne et teledetection - caracteristiques physiques','',0,0,'',1,'','','unimarc_field_121b.pl',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('121','a','Documents cartographiques-caracteristiques physiques','',0,0,'',1,'','','unimarc_field_121a.pl',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('120','a','Donnees codees sur les documents cartographiques-generalites','',0,0,'',1,'','','unimarc_field_120.pl',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('830','a','texte de la note','note',0,0,'',8,'','',NULL,NULL,NULL,'CART','');
INSERT INTO marc_subfield_structure VALUES ('801','c','date de la transaction','',0,0,'',8,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('801','g','règles de catalogage utilisées','',0,0,'',8,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('801','b','agence de catalogage','',0,1,'',8,'SOURCES','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('801','a','pays','',0,0,'',8,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('801','2','code du format utilisé','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('722','f','dates','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('722','a','élément d\'entrée','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('722','4','code de fonction','',0,1,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('721','a','élément d\'entrée','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('721','f','dates','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('722','3','numéro de la notice d\'autorité','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('721','4','code de fonction','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('721','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('720','f','dates','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('720','a','élément d\'entrée','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('720','3','numéro de la notice d\'autorité','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('720','4','code de fonction','',0,1,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('712','p','affiliation ou adresse','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('712','g','élément rejeté','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('712','h','partie du nom autre que l\'élément d\'entrée et que l\'élément rejeté','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('712','f','date du congrès','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('712','e','lieu du congrès','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('712','d','numéro de congrès et/ou de session','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('712','b','subdivision','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('712','c','élément ajouté au nom ou qualificatif','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('712','a','élément d\'entrée','',0,0,'',7,'','CO','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('712','5','institution à laquelle s\'applique cette zone','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('712','4','code de fonction','',0,0,'',7,'','','unimarc_field_700-4.pl',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('711','g','élément rejeté','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('711','h','partie du nom autre que l\'élément d\'entrée et que l\'élément rejeté','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('712','3','numéro de la notice d\'autorité','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('711','p','affiliation ou adresse','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('711','e','lieu du congrès','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('711','f','date du congrès','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('711','d','numéro de congrès et/ou de session','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('711','a','élément d\'entrée','',0,0,'',7,'','CO','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('711','b','subdivision','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('711','c','élément ajouté au nom ou qualificatif','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('711','4','code de fonction','',0,0,'',7,'','','unimarc_field_700-4.pl',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('711','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('710','e','lieu du congrès','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('710','p','affiliation ou adresse','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('710','g','élément rejeté','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('710','h','partie du nom autre que l\'élément d\'entrée','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('710','f','date du congrès','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('710','d','numéro de congrès et/ou de session','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('710','c','élément ajouté au nom ou qualificatif','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('710','b','subdivision','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('710','a','élément d\'entrée','',0,0,'',7,'','CO','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('710','4','code de fonction','',0,0,'',7,'','','unimarc_field_700-4.pl',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('710','3','numéro de la notice d\'autorité','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('702','p','affiliation ou adresse','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('702','g','forme développée des initiales du prénom','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('702','f','dates','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('702','d','chiffres romains','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('702','c','qualificatifs autres que les dates','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('702','a','élément d\'entrée','',0,0,'',7,'','NP','unimarc_field_700_701_702.pl',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('702','b','partie du nom autre que l\'élément d\'entrée','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('702','5','institution à laquelle s\'applique cette zone','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('702','4','code de fonction','',0,0,'',7,'','','unimarc_field_700-4.pl',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('702','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('701','p','affiliation ou adresse','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('701','g','forme développée des initiales du prénom','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('701','f','dates','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('701','d','chiffres romains','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('701','c','qualificatifs autres que les dates','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('701','a','élément d\'entrée','',0,0,'',7,'','NP','unimarc_field_700_701_702.pl',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('701','b','partie du nom autre que l\'élément d\'entrée','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('700','p','affiliation ou adresse','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('701','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('701','4','code de fonction','',0,0,'',7,'','','unimarc_field_700-4.pl',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('700','g','forme développée des initiales du prénom','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('700','f','dates','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('700','d','chiffres romains','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('700','c','qualificatifs autres que les dates','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('700','b','partie du nom autre que l\'élément d\'entrée','',0,0,'',7,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('700','a','élément d\'entrée','auteur',0,0,'',7,'','NP','unimarc_field_700_701_702.pl',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('700','4','code de fonction','',0,0,'',7,'','','unimarc_field_700-4.pl',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('700','3','numéro de la notice d\'autorité','',0,0,'',7,'itemtypes','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('676','z','langue d\'édition','',0,0,'',6,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('676','a','indice Dewey','',0,0,'biblioitems.dewey',6,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('676','v','édition','',0,0,'',6,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('661','a','code de date','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('620','d','ville','lieu d\'édition',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('620','c','département, comté, etc','lieu d\'édition',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('620','b','Etat, région, etc','lieu d\'édition',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('620','3','numéro de la ville d\'autorité','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('620','a','pays','lieu d\'édition',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('615','x','subdivision de la catégorie sujet','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('615','n','catégorie sujet sous forme codée','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('615','m','subdivision de la catégorie sujet sous forme codée','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('615','a','catégorie sujet','sujet',0,0,'',6,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('615','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('615','2','code du système d\'indexation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('610','a','descripteur','sujet',1,0,'',6,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('610','5','descripteur','sujet',1,0,'bibliosubject.subject',6,'','MC','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('608','z','subdivision chronologique','',0,1,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('608','y','subdivision géographique','',0,1,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('608','x','subdivision du sujet','',0,1,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('608','a','élément d\'entrée','sujet',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('608','3','numéro de la notice d\'autorité','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('608','5','institution à laquelle s\'applique cette zone','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('605','x','subdivision du sujet','',0,1,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('605','y','subdivision géographique','',0,1,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('608','2','code du système d\'indexation','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('607','z','subdivision chronologique','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('607','y','subdivision géographique','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('607','x','subdivision du sujet','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('607','a','élément d\'entrée','sujet',0,0,'',6,'','NP','unimarc_field_700-4.pl',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('607','2','code du système d\'indexation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('607','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('606','z','subdivision chronologique','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('606','y','subdivision géographique','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('606','x','subdivision du sujet','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('606','a','élément d\'entrée','sujet',0,0,'',6,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('606','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('606','2','code du système d\'indexation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('605','z','subdivision chronologique','',0,1,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('605','q','version','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('605','m','langue','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('605','n','autres informations','',0,1,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('605','k','date de publication','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('605','l','sous-vedettes de forme','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('605','i','nom de partie','',0,1,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('605','h','numéro de la partie','',0,1,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('605','a','élément d\'entrée','sujet',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('605','3','numéro de la notice d\'autorité','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('605','2','code du système d\'indexation','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('604','1','données de liens','',0,1,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('602','z','subdivision chronologique','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('602','y','subdivision géographique','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('602','f','dates','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('602','x','subdivision de sujet','',0,1,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('602','3','numéro de la notice d\'autorité','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('602','a','élément d\'entrée','sujet',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('602','2','code du système d\'indexation','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('601','z','subdivision chronologique','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('601','y','subdivision géographique','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('601','x','subdivision de sujet','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('601','h','partie du nom autre que l\'élément d\'entrée ou l\'élément rejeté','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('601','g','élément rejeté','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('601','f','date du congrès','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('601','e','lieu du congrès','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('601','d','numéro de congrès et/ou de session','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('601','c','élément ajouté au nom','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('601','b','subdivision','sujet',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('601','a','élément d\'entrée','sujet',0,0,'',6,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('601','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('601','2','code du système d\'indexation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('600','y','subdivision géographique','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('600','z','subdivision chronologique','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('600','x','subdivision du sujet','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('600','g','forme développée des initiales du prénom','',0,0,'',6,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('600','f','dates','',0,0,'',6,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('600','d','chiffres romains','',0,0,'',6,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('600','c','qualificatifs autre que les dates','',0,0,'',6,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('600','b','partie autre que l\'élément d\'entrée','',0,0,'',6,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('600','a','élément d\'entrée','sujet',0,0,'',6,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('600','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('541','i','titre de partie','',0,0,'',5,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('541','z','langue du titre traduit','',0,0,'',5,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('600','2','code du système d\'indexation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('541','h','numéro de partie','',0,0,'',5,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('541','e','complément du titre','',0,0,'',5,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('541','a','titre traduit','titre traduit',0,0,'',5,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('540','a','titre ajouté par le catalogueur','',0,0,'',5,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('517','e','complément du titre','',0,0,'',5,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('517','a','Variante du titre','',0,0,'',5,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('515','z','langue du titre','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('515','n','autres informations','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('515','j','volume ou dates associés au titre','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('515','i','titre de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('515','h','numéro de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('515','a','titre courant','',0,0,'',5,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('515','e','complément du titre','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('510','z','langue du titre','',0,0,'',5,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('510','h','numéro de partie','',0,0,'',5,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('510','i','titre de partie','',0,0,'',5,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('510','j','volume ou dates associés au titre','',0,0,'',5,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('510','n','autres informations','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('510','e','complément du titre','',0,0,'',5,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('510','a','titre parallèle','',0,0,'',5,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('488','y','ISBN/numéro international normalisé de document musical','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('488','x','ISSN','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('488','u','URL','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('488','v','numéro de volume','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('488','t','titre','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('488','p','collation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('488','i','titre de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('488','h','numéro de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('488','e','mention d\'édition','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('488','d','date de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('488','5','institution à laquelle s\'applique cette zone','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('488','a','auteur','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('488','c','lieu de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('488','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('488','0','numéro d\'identification de la notice','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('464','y','ISBN/numéro international normalisé de document musical','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('464','v','numéro de volume','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('464','x','ISSN','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('464','u','URL','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('464','p','collation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('464','t','titre','',1,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('464','a','auteur','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('464','c','lieu de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('464','d','date de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('464','e','mention d\'édition','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('464','h','numéro de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('464','i','titre de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('464','5','institution à laquelle s\'applique cette zone','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('464','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('464','0','numéro d\'identification de la notice','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('463','y','ISBN/numéro international normalisé de document musical','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('463','x','ISSN','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('463','v','numéro de volume','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('463','u','URL','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('463','i','titre de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('463','t','titre','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('463','p','collation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('463','h','numéro de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('463','e','mention d\'édition','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('463','a','auteur','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('463','c','lieu de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('463','d','date de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('463','5','institution à laquelle s\'applique cette zone','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('463','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('463','0','numéro d\'identification de la notice','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('462','y','ISBN/numéro international normalisé de document musical','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('462','x','ISSN','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('462','v','numéro de volume','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('462','u','URL','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('462','t','titre','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('462','p','collation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('462','i','titre de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('462','d','date de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('462','e','mention d\'édition','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('462','h','numéro de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('462','c','lieu de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('462','a','auteur','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('462','5','institution à laquelle s\'applique cette zone','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('462','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('462','0','numéro d\'identification de la notice','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('461','y','ISBN/numéro international normalisé de document musical','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('461','x','ISSN','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('461','v','numéro de volume','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('461','u','URL','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('461','t','titre','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('461','i','titre de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('461','p','collation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('461','h','numéro de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('461','e','mention d\'édition','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('461','d','date de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('461','c','lieu de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('461','a','auteur','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('461','0','numéro d\'identification de la notice','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('461','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('461','5','institution à laquelle s\'applique cette zone','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('456','y','ISBN/numéro international normalisé de document musical','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('456','x','ISSN','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('456','v','numéro de volume','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('456','t','titre','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('456','u','URL','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('456','i','titre de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('456','p','collation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('456','h','numéro de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('456','e','mention d\'édition','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('456','d','date de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('456','c','lieu de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('456','5','institution à laquelle s\'applique cette zone','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('456','a','auteur','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('456','0','numéro d\'identification de la notice','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('456','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('455','y','ISBN/numéro international normalisé de document musical','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('455','x','ISSN','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('455','v','numéro de volume','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('455','t','titre','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('455','u','URL','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('455','p','collation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('455','i','titre de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('455','h','numéro de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('455','e','mention d\'édition','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('455','d','date de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('455','c','lieu de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('455','a','auteur','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('455','5','institution à laquelle s\'applique cette zone','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('455','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('455','0','numéro d\'identification de la notice','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('454','y','ISBN/numéro international normalisé de document musical','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('454','x','ISSN','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('454','t','titre','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('454','u','URL','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('454','v','numéro de volume','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('454','p','collation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('454','i','titre de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('454','h','numéro de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('454','e','mention d\'édition','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('454','d','date de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('454','c','lieu de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('454','a','auteur','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('454','5','institution à laquelle s\'applique cette zone','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('454','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('454','0','numéro d\'identification de la notice','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('453','x','ISSN','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('453','y','ISBN/numéro international normalisé de document musical','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('453','u','URL','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('453','v','numéro de volume','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('453','t','titre','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('453','p','collation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('453','i','titre de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('453','h','numéro de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('453','e','mention d\'édition','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('453','d','date de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('453','c','lieu de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('453','a','auteur','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('453','5','institution à laquelle s\'applique cette zone','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('453','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('453','0','numéro d\'identification de la notice','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('452','y','ISBN/numéro international normalisé de document musical','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('452','x','ISSN','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('452','t','titre','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('452','u','URL','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('452','v','numéro de volume','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('452','p','collation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('452','i','titre de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('452','h','numéro de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('452','e','mention d\'édition','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('452','c','lieu de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('452','d','date de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('452','5','institution à laquelle s\'applique cette zone','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('452','a','auteur','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('452','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('451','y','ISBN/numéro international normalisé de document musical','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('452','0','numéro d\'identification de la notice','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('451','v','numéro de volume','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('451','x','ISSN','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('451','t','titre','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('451','u','URL','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('451','p','collation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('451','i','titre de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('451','h','numéro de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('451','d','date de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('451','e','mention d\'édition','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('451','a','auteur','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('451','c','lieu de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('451','5','institution à laquelle s\'applique cette zone','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('451','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('451','0','numéro d\'identification de la notice','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('411','x','ISSN','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('411','y','ISBN/numéro international normalisé de document musical','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('411','v','numéro de volume','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('411','u','URL','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('411','t','titre','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('411','p','collation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('411','i','titre de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('411','c','lieu de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('411','d','date de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('411','e','mention d\'édition','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('411','h','numéro de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('411','5','institution à laquelle s\'applique cette zone','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('411','a','auteur','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('411','0','numéro d\'identification de la notice','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('411','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('410','y','ISBN/numéro international normalisé de document musical','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('410','u','URL','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('410','v','numéro de volume','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('410','x','ISSN','',0,0,'',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('410','t','titre','',0,0,'biblio.serial',4,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('410','p','collation','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('410','i','titre de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('410','h','numéro de section ou de partie','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('410','e','mention d\'édition','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('410','a','auteur','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('410','c','lieu de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('410','d','date de publication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('410','3','numéro de la notice d\'autorité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('410','5','institution à laquelle s\'applique cette zone','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('410','0','numéro d\'identification de la notice','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('345','d','disponibilité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('345','b','numéro d\'éditeur','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('345','c','support','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('345','a','source de l\'acquisition, adresse pour l\'abonnement','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('332','a',' note sur les titres choisis','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('333','a','texte de la note','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('327','a','texte de la note','',1,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('330','a','texte de la note','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('315','a','texte de la note','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('324','a','texte de la note','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('325','a','texte de la note','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('314','a','texte de la note','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('313','a','texte de la note','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('312','a','texte de la note','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('311','a','texte de la note','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('307','a','texte de la note','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('308','a','texte de la note','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('305','a','texte de la note','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('306','a','texte de la note','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('304','a','texte de la note','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('303','a','texte de la note','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('302','a','texte de la note','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('300','a','texte de la note','',0,0,'',3,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('225','z','langue du titre parallèle','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('225','x','ISSN de la collection','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('225','v','numéro du volume','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('225','i','titre de la sous-collection','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('225','h','numéro de la sous-collection','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('225','f','mention de responsabilité','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('225','e','compléments de titre de la collection','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('225','d','titre parallèle de la collection','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('215','e','matériel d\'accompagnement','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('225','a','titre de la collection','',0,0,'',2,'','','unimarc_field_225a.pl',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('215','d','format','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('215','c','autres caractéristiques matérielles','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('215','a','indication du type de document et importance matérielle','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('211','a','date','',0,0,NULL,NULL,NULL,NULL,'',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('210','h','date de fabrication','',0,1,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('210','g','nom du fabricant','',0,1,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('210','f','adresse du fabricant','',0,1,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('210','e','lieu de publication de fabrication','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('210','d','date de publication, de diffusion','',0,0,'biblioitems.publicationyear',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('210','c','nom de l\'éditeur, du diffuseur','',0,0,'',2,'','EDITORS','unimarc_field_210c.pl',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('210','b','adresse de l\'éditeur, du diffuseur','',1,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('210','a','lieu de publication, de diffusion, etc','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('205','g','mention de responsabilité suivante','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('205','f','mention de responsabilité relative à l\'édition','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('205','d','mention parallèle d\'édition','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('205','b','mention de parution','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('205','a','mention d\'édition','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('200','z','langue du titre parallèle','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('200','v','numéro de volume','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('200','i','titre de partie','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('200','h','numéro de partie','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('200','g','première mention de responsabilité suivante','',0,0,'additionalauthors.author',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('200','f','première mention de responsabilité','',0,0,'biblio.author',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('200','d','titre parallèle','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('200','e','complément du titre','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('200','c','titre propre d\'un auteur différent','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('200','b','indication générale du type de document','',0,0,'',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('200','a','titre propre','',1,1,'biblio.title',2,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('200','5','nom de l\'institution à laquelle s\'applique cette zone','',1,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('122','a','Période  : de 9999 avant J.C. à nos jours','',0,1,'',1,'','','unimarc_field_122.pl',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('102','b','lieu  d\'édition','',0,0,'',1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('102','a','pays d\'édition','',0,0,'',1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('101','j','langue des sous-titres','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('101','i','langue des textes d\'accompagnement','',0,0,'',1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('101','h','langue d\'un livret','',0,0,'',1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('101','g','langue du titre propre si elle diffère de la langue du texte ou de la bande son','',0,0,'',1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('101','f','langue de la page de titre si elle diffère de celle du texte','',0,0,'',1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('101','e','langue de la table des matières','',0,0,'',1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('101','d','langue d\'un résumé','',0,0,'',1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('101','c','langue de l\'oeuvre originale','',0,0,'',1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('101','b','langue d\'un texte intermédiaire quand le document n\'est pas une traducti','',0,0,'',1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('101','a','langue d\'un texte, d\'une bande son, etc','',0,0,'',1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('100','a','données générales de traitement','',0,0,'',1,'','','unimarc_field_100.pl',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('001','@','Numéro d\'identification notice','',0,0,'',-1,'','','',NULL,NULL,'CART',NULL);
INSERT INTO marc_subfield_structure VALUES ('123','d','Coordonnees - longitude ouest','',0,0,'',1,'','','unimarc_field_123d.pl',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('123','e','Coordonnees - longitude est','',0,0,'',1,'','','unimarc_field_123e.pl',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('123','f','Coordonnees - longitude nord','',0,0,'',1,'','','unimarc_field_123f.pl',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('123','g','Coordonnees - longitude sud','',0,0,'',1,'','','unimarc_field_123g.pl',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('123','h','Echelle angulaire','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('123','i','Declinaison - limite nord','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('123','j','Declinaison - limite sud','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('123','k','Ascension droite - limite est','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('123','m','Ascension droite - limite ouest','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('123','n','Equinoxe','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('124','a','Origine de l\'image','',0,0,'',1,'','','unimarc_field_124a.pl',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('124','b','Forme du document cartographique','',0,0,'',1,'','','unimarc_field_124b.pl',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('124','c','Presentation technique dans le cas d\'images.','',0,0,'',1,'','','unimarc_field_124c.pl',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('124','d','Position de la base pour les images photographiques ou de teledetection','',0,0,'',1,'','','unimarc_field_124d.pl',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('124','e','Categorie de satellite pour la teledetection','',0,0,'',1,'','','unimarc_field_124e.pl',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('124','f','Nom du satellite pour la teledetection','',0,0,'',1,'','','unimarc_field_124f.pl',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('124','g','Technique d\'enregistrement pour les images de teledetection','',0,0,'',1,'','','unimarc_field_124g.pl',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('131','a','Ellipsoide','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('131','b','Donnees horizontales','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('131','c','Quadrillage et systeme de reference','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('131','d','Recouvrement et systeme de reference','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('131','e','Quadrillage et systeme de reference secondaire','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('131','f','Donnees verticales','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('131','g','Unite de mesure pour l\'altitude','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('131','h','Intervalle des courbes de niveau','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('131','i','Intervalle des courbes de niveau supplementaires','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('131','j','Unite de mesure de bathymetrie','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('131','k','Intervalle bathymetrique','',0,0,'',1,'','','',0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('131','l','Intervalle bathymetrique supplementaire','',0,0,'',1,'','',NULL,0,0,'CART','');
INSERT INTO marc_subfield_structure VALUES ('206','a','Mention de donnees mathematiques','',0,0,'',2,'','',NULL,0,0,'CART','');
