<!--
 list of Classes to be included in /catalogue/index.html and cat/index.html
 This is a qick-fix - These should really be fetched from the database
-->
<option value="E">Easy / Picture Books
<option value="ER">Easy Reader	
<option value="JNF">Młodzieżowa Nie-Fikcja
<option value="JF">Fikcja Młodzieżowa
<option value="TREF">Teacher Reference
<option value="FYA">Young Adult Fiction	
<option value="REF">Reference Books
<option value="F">Fikcja
<option value="NF">Nie-Fikcja
<option value="CD">Dysk Kompaktowy
<!--	<option value="E|ER">Easy Books-->

