	<!-- MENUS -->
	<div id="menuline" style="font-size:11pt;margin-top:20px;margin-bottom:20px;">
		<span class="spacer">&nbsp;</span>
		<A href='javascript:delBasket()' class="menu">Vider</A>
		<span class="basketspacer">&nbsp;</span>
		<A href='javascript:delSelRecords()' class="menu">Effacer la sélection</A>
		<span class="basketspacer">&nbsp;</span>
		<A href='javascript:formAddress()' class="menu">Envoyer</A>
		<span class="basketspacer">&nbsp;</span>
		<A href='javascript:printBasket()' class="menu">Imprimer</A>
		<span class="basketspacer">&nbsp;</span>
		<A href='javascript:quit()' class="menu">Quitter</A>
	</div>
