<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<html>
<head>
	<title>Panier de notices OPAC</title>
	<link rel="stylesheet" type="text/css" href="<!-- TMPL_VAR name="themelang" -->/includes/opac.css">
	<script src='/js/basket.js'></script>
	<SCRIPT language='javascript'>
		var MSG_NO_RECORD_SELECTED = "Aucune notice sélectionnée";
		var MSG_NO_RECORD_ADDED = "Aucune notice ajoutée";
		var MSG_CONFIRM_DEL_BASKET = "Voulez-vous supprimer toutes les notices du panier ?"
		var MSG_CONFIRM_DEL_RECORDS = "Voulez-vous effacer les notices sélectionnées ?";
	</SCRIPT>
</head>
