<ul>
	<li><a href="/cgi-bin/koha/acqui/supplier.pl?op=enter">Ajout d'un fournisseur</a></li>
	<li><a href="/cgi-bin/koha/acqui/lateorders.pl">Commandes en retard</a></li>
	<li><a href="/cgi-bin/koha/acqui/histsearch.pl">Recherche historique</a></li>
	<li><a href="/cgi-bin/koha/suggestion/acceptorreject.pl?op=aorr_confirm">Suggestions en attente</a></li>
	<li><a href="/cgi-bin/koha/admin/aqbookfund.pl">Paramètres</a></li>
</ul>