<h5>Préférences système</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/systempreferences.pl">Préférences système</a></li>
</ul>

<h5>Paramètres de base</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/branches.pl">Sites de la bibliothèque</a></li>
	<li><a href="/cgi-bin/koha/admin/aqbookfund.pl">Postes et budgets</a></li>
	<li><a href="/cgi-bin/koha/admin/currency.pl">Devises et taux de change</a></li>
	<li><a href="/cgi-bin/koha/admin/itemtypes.pl">Types de documents et règles de prêt.</a></li>
</ul>

<h5>Adhérents et circulation</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/categorie.pl">Catégories adhérent</a></li>
	<li><a href="/cgi-bin/koha/admin/cities.pl">Gestion des communes</a></li>
	<li><a href="/cgi-bin/koha/admin/roadtype.pl">Types de voie</a></li>
	<li><a href="/cgi-bin/koha/admin/issuingrules.pl">Règles de circulation</a></li>
	<li><a href="/cgi-bin/koha/admin/finesrules.pl">Règles de retard</a></li>
</ul>

<h5>Catalogue</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/authorised_values.pl">Valeurs autorisées</a></li>
	<li><a href="/cgi-bin/koha/admin/biblio_framework.pl">Grille de catalogage MARC</a></li>
	<li><a href="/cgi-bin/koha/admin/koha2marclinks.pl">Liens Koha => MARC</a></li>
	<li><a href="/cgi-bin/koha/admin/checkmarc.pl">Validation grilles de catalogage</a></li>
    <li><a href="/cgi-bin/koha/admin/authtypes.pl">Grille d'autorité Marc</a></li>
    <li><a href="/cgi-bin/koha/admin/classsources.pl">Sources de classification</a></li>
</ul>

<h5>Paramètres divers</h5>

<ul>
	<li><a href="/cgi-bin/koha/admin/printers.pl">Imprimantes</a></li>
	<li><a href="/cgi-bin/koha/admin/z3950servers.pl">Serveurs Z39.50</a></li>
</ul>
