<br clear="all" />

<div class="center">
<a href="/cgi-bin/koha/mainpage.pl">Accueil</a> ||
<a href="/cgi-bin/koha/catalogue/search.pl">Catalogue</a> ||
<a href="/cgi-bin/koha/members/members-home.pl">Adhérents</a> ||
<a href="/cgi-bin/koha/acqui/acqui-home.pl">Acquisitions</a> ||
<a href="/cgi-bin/koha/circ/circulation.pl">Circulation</a> ||
<a href="/cgi-bin/koha/reports-home.pl">Bilans et statistiques</a> ||
<a href="/cgi-bin/koha/admin-home.pl">Paramètres</a> ||
<a href="/cgi-bin/koha/about.pl">A propos</a> || 
Aide
</div>

</body>
</html>
