<div id="submenu">
<ul>
	<li>    <a href="/cgi-bin/koha/members/memberentry.pl?op=add&amp;category_type=A">Ajouter un adulte</a></li>
	<li>    <a href="/cgi-bin/koha/members/memberentry.pl?op=add&amp;category_type=C">Ajouter un enfant</a></li>
	<li>    <a href="/cgi-bin/koha/members/memberentry.pl?op=add&amp;category_type=P">Ajouter un professionnel</a></li>
	<li>    <a href="/cgi-bin/koha/members/memberentry.pl?op=add&amp;category_type=I">Ajouter une collectivité</a></li>
</ul>
</div>