<div id="submenu">
    <a href="/cgi-bin/koha/circ/circulation.pl">Prêts</a> <a href="/cgi-bin/koha/circ/returns.pl">Retours</a> <a href="/cgi-bin/koha/circ/branchtransfers.pl">Transferts</a> <a href="/cgi-bin/koha/circ/selectbranchprinter.pl">Choix du site</a> <a href="/cgi-bin/koha/circ/pendingreserves.pl" title="reserves waiting to have an item affected">Réservations à traiter</a> <a href="/cgi-bin/koha/circ/waitingreserves.pl" title="reserves waiting for member pickup">Réservations en attente</a> <a href="/cgi-bin/koha/circ/transferstodo.pl" title="transfers to do from your library">Transferts à faire</a> <a href="/cgi-bin/koha/circ/transferstoreceive.pl" title="transfers to receive at your library">Transfertsà recevoir</a> <a href="/cgi-bin/koha/circ/branchoverdues.pl">Retards</a> <a href="/cgi-bin/koha/circ/stats.pl?time=yesterday">Etat de caisse (aujourd'hui)</a> 
</div>

<div id="main">
