<div id="submenu">
    <a href="/cgi-bin/koha/acqui/supplier.pl?op=enter">Ajout fournisseur</a> <a href="/cgi-bin/koha/acqui/lateorders.pl">Commandes en retard</a> <a href="/cgi-bin/koha/acqui/histsearch.pl">Recherche historique</a> <a href="/cgi-bin/koha/suggestion/acceptorreject.pl?op=aorr_confirm">Gestion suggestions</a> <a href="/cgi-bin/koha/admin/aqbookfund.pl">Paramètres</a>
</div>

<div id="main">
