<div id="submenu">
    <a href="/cgi-bin/koha/tools/tools-home.pl">Accueil</a> <a href="/cgi-bin/koha/tools/holidays.pl">Jours fériés</a> <a href="/cgi-bin/koha/tools/koha-news.pl">Nouvelles</a> <a href="/cgi-bin/koha/tools/inventory.pl">Inventaire/récolement</a> <a href="/cgi-bin/koha/tools/cleanborrowers.pl">Apurement des adhérents</a> <a href="/cgi-bin/koha/tools/itemslost.pl">Exemplaires perdus</a> <a href="/cgi-bin/koha/tools/export.pl">Exportation</a><a href="/cgi-bin/koha/tools/import.pl">Importation</a><a href="/cgi-bin/koha/tools/letter.pl">Lettres</a><a href="/cgi-bin/koha/tools/breeding.pl">Reservoir</a> <a href="/cgi-bin/koha/tools/barcodes.pl">Codes à barres</a> <a href="/cgi-bin/koha/tools/overduerules.pl">Règles de retard</a> <a href="/cgi-bin/koha/tools/viewlog.pl">Visualiseur de log</a>
</div>

<div id="main">
