<div id="submenu">
    <a href="/cgi-bin/koha/circ/selectbranchprinter.pl">Choix du site</a> <a href="/cgi-bin/koha/circ/pendingreserves.pl" title="holds to retrieve off the shelf">Réservations à traiter</a> <a href="/cgi-bin/koha/circ/waitingreserves.pl" title="holds waiting for patron pickup">Réservations en attente</a> <a href="/cgi-bin/koha/circ/transferstodo.pl" title="transfers to do from your library">Transferts à faire</a> <a href="/cgi-bin/koha/circ/transferstoreceive.pl" title="transfers to receive at your library">Transferts à recevoir</a> <a href="/cgi-bin/koha/circ/overdue.pl">Retards</a> <a href="/cgi-bin/koha/circ/branchoverdues.pl">Amendes</a7> <a href="/cgi-bin/koha/circ/stats.pl?time=yesterday">Etat de caisse (aujourd'hui)</a> 
</div>

<div id="main">
