<div id="submenu">
<ul>
	<li>    <a href="/cgi-bin/koha/circ/selectbranchprinter.pl">Définir un site</a></li>
	<li>    <a href="/cgi-bin/koha/circ/pendingreserves.pl" title="Réservations à mettre de coté">Réservations à traiter</a></li>
	<li>    <a href="/cgi-bin/koha/circ/waitingreserves.pl" title="Réservations mis de coté pour : %s">Réservations mises de coté</a></li>
	<li>    <a href="/cgi-bin/koha/circ/transferstodo.pl" title="Transferts à faire depuis votre site">Transferts à effectuer</a></li>
	<li>    <a href="/cgi-bin/koha/circ/transferstoreceive.pl" title="Transferts en cours vers votre site">Transfert à recevoir</a></li>
	<li>    <a href="/cgi-bin/koha/circ/overdue.pl">Retards</a></li>
	<li>    <a href="/cgi-bin/koha/circ/branchoverdues.pl">Amendes</a></li>
	<li>    <a href="/cgi-bin/koha/circ/stats.pl?time=yesterday">Etat de caisse quotidien</a></li>
</ul>
</div>