<div id="submenu">
    <a href="/cgi-bin/koha/members/memberentry.pl?op=add&amp;category_type=A">Inscription adulte</a><a href="/cgi-bin/koha/members/memberentry.pl?op=add&amp;category_type=C">Inscription enfant</a><a href="/cgi-bin/koha/members/memberentry.pl?op=add&amp;category_type=P">Inscription professionnel</a><a href="/cgi-bin/koha/members/memberentry.pl?op=add&amp;category_type=I">Inscription collectivité</a>
</div>

<div id="main">
