<div id="submenu">
    <p>
        <a href="/cgi-bin/koha/admin/branches.pl">Sites</a><a href="/cgi-bin/koha/admin/aqbookfund.pl">Budgets</a><a href="/cgi-bin/koha/admin/itemtypes.pl">Types documents</a> <a href="/cgi-bin/koha/admin/categorie.pl">Catégories d'adhérent</a><a href="/cgi-bin/koha/admin/issuingrules.pl">Règles de prêt</a>
    </p>
    <p>
        <a href="/cgi-bin/koha/admin/biblio_framework.pl">Grilles catalogage</a> <a href="/cgi-bin/koha/admin/authtypes.pl">Grilles Autorités</a> <a href="/cgi-bin/koha/admin/authorised_values.pl">Valeurs autorisées</a>
    </p>
</div>

<div id="main">
