<div id="submenu">
    <p>
<ul>
	<li>        <a href="/cgi-bin/koha/admin/branches.pl">Sites</a></li>
	<li>        <a href="/cgi-bin/koha/admin/aqbookfund.pl">Poste budgétaire</a></li>
	<li>        <a href="/cgi-bin/koha/admin/itemtypes.pl">Types de document</a></li>
	<li>        <a href="/cgi-bin/koha/admin/categorie.pl">Catégories adhérent</a></li>
	<li>        <a href="/cgi-bin/koha/admin/issuingrules.pl">Règles de prêt</a></li>
</ul>
    </p>
    <p>
<ul>
	<li>        <a href="/cgi-bin/koha/admin/biblio_framework.pl">Grille de catalogage</a></li>
	<li>        <a href="/cgi-bin/koha/admin/authtypes.pl">Grilles d'autorité</a></li>
	<li>        <a href="/cgi-bin/koha/admin/authorised_values.pl">Valeurs autorisées</a></li>
</ul>
    </p>
</div>
