<div id="submenu">
    <a href="/cgi-bin/koha/catalogue/search.pl">Recherche</a> <a href="/cgi-bin/koha/cataloguing/addbooks.pl">Catalogage </a> <a href="/cgi-bin/koha/cataloguing/addbiblio.pl">Ajout notice MARC</a> <a href="/cgi-bin/koha/serials/serials-home.pl">Abonnements</a> <a href="/cgi-bin/koha/bookshelves/shelves.pl">Etagères virtuelles</a> <a href="/cgi-bin/koha/reviews/reviewswaiting.pl">Gestion des commentaires</a>
</div>

<div id="main">
