<div id="submenu">
<ul>
	<li>        <a href="/cgi-bin/koha/serials/serials-home.pl">Accueil périodiques</a></li>
	<li>        <a href="/cgi-bin/koha/serials/claims.pl">Réclamations</a></li>
	<li>        <a href="/cgi-bin/koha/serials/subscription-add.pl">Ajouter un abonnement</a></li>
	<li>        <a href="/cgi-bin/koha/serials/checkexpiration.pl">Vérificater dates d'expiration</a></li>
</ul>
</div>