<h5>Assistant de bilan</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/acquisitions_stats.pl">Acquisitions</a></li>
		<li><a href="/cgi-bin/koha/reports/borrowers_stats.pl">Adhérents</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_stats.pl">Catalogue</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_stats.pl">Circulation</a></li>
	</ul>


	<h5>Les plus</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/bor_issues_top.pl">Adhérents empruntant le plus</a></li>
		<li><a href="/cgi-bin/koha/reports/cat_issues_top.pl">Document(s) les plus prétés</a></li>
	</ul>
	
	<h5>Inactif</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/borrowers_out.pl">Adhérents qui n'empruntent jamais</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_out.pl">Document(s) jamais prétés</a></li>
	</ul>


	<h5>Autres</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/itemslost.pl">Exemplaires perdus</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=itemtypes">Catalogue par type de document</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=issues_by_borrower_category">Prêts par catégorie d'adhérent</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_avg_stats.pl">Durée moyenne du prêt</a></li>
	</ul>
