<ul>
	<li><a href="/cgi-bin/koha/tools/tools-home.pl">Accueil outils</a></li>
	<li><a href="/cgi-bin/koha/tools/holidays.pl">Jours fériés</a></li>
	<li><a href="/cgi-bin/koha/tools/koha-news.pl">Nouvelles</a></li>
	<li><a href="/cgi-bin/koha/tools/inventory.pl">Inventaire/récolement</a></li>
	<li><a href="/cgi-bin/koha/tools/cleanborrowers.pl">Apurer les adhérents</a></li>
	<li><a href="/cgi-bin/koha/tools/export.pl">Exportation</a></li>
	<li><a href="/cgi-bin/koha/tools/import.pl">Importer</a></li>
	<li><a href="/cgi-bin/koha/tools/letter.pl">NotificationsNotes</a></li>
	<li><a href="/cgi-bin/koha/tools/overduerules.pl">Déclencheur de notification</a></li>
	<li><a href="/cgi-bin/koha/tools/breeding.pl">Réservoir</a></li>
	<li><a href="/cgi-bin/koha/labels/label-home.pl">Etiquettes</a></li>
	<li><a href="/cgi-bin/koha/tools/viewlog.pl">Visualiseur des logs</a></li>
</ul>
