</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="<!-- TMPL_VAR NAME='themelang' -->/includes/favicon.ico" type="image/x-icon" />
<style type="text/css"> 
	@import url(<!-- TMPL_VAR NAME='themelang' -->/includes/intranet.css);
</style>
<link rel="stylesheet" type="text/css" href="<!-- TMPL_VAR name="themelang" -->/includes/calendar/calendar-system.css" />
<script type="text/javascript" src="<!-- TMPL_VAR name='themelang' -->/includes/calendar/calendar.js"></script>
<script type="text/javascript" src="<!-- TMPL_VAR name="themelang"-->/includes/calendar/calendar-en.js"></script>
<script type="text/javascript" src="<!-- TMPL_VAR name="themelang" -->/includes/calendar/calendar-setup.js"></script>
</head>

<body>