<div id="submenu">
        <a href="/cgi-bin/koha/serials/serials-home.pl">home</a>
        <a href="/cgi-bin/koha/serials/serial-issues.pl">Serials issues</a>
        <a href="/cgi-bin/koha/serials/acqui-search.pl">Supplier search</a>
        <a href="/cgi-bin/koha/serials/subscription-bib-search.pl">Subscription search</a>
        <a href="/cgi-bin/koha/serials/subscription-bib-search.pl">Search subscription</a>
        <a href="/cgi-bin/koha/serials/lateissues.pl">Late issue</a>
        <a href="/cgi-bin/koha/serials/subscription-add.pl">Add a subscription</a>
        <a href="/cgi-bin/koha/serials/viewalerts.pl">View alerts</a>
</div>
<div id="main">