</title>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<meta http-equiv="Content-Language" content="en-us" />
<style type="text/css"> 
	@import url(<TMPL_VAR NAME="themelang">/includes/opac.css);
</style>
<script type="text/javascript" language="javascript" src="<TMPL_VAR NAME="themelang">/includes/script.js"></script>
<script type="text/javascript" language="javascript" src="<TMPL_VAR NAME="themelang">/includes/basket.js"></script>
<script type="text/javascript" language="javascript">
	var MSG_BASKET_EMPTY = "You book bag is currently empty";
	var MSG_RECORD_IN_BASKET = "This item is already in your book bag";
	var MSG_RECORD_ADDED = "This item has been added to your book bag";
	var MSG_NRECORDS_ADDED = " item(s) added to your book bag";
	var MSG_NRECORDS_IN_BASKET = "already in the bag";
	var MSG_NO_RECORD_SELECTED = "No item was selected";
	var MSG_NO_RECORD_ADDED = "No item was added to your book bag";
</script>
</head>
<body>