<div id="masthead">
<h1>Library Catalog Search</h1>
<div class="menu"><form action="/cgi-bin/koha/opac-search.pl" method="post">
<a href="/cgi-bin/koha/opac-main.pl">Search Home</a> | <a href="" onclick="openBasket(); return false;" title="A &quot;shopping cart&quot; for your selections">Book Bag</a> | <label for="value">Search the Catalog</label>
  <input type="hidden" name="op" value="do_search" />
			<input type="hidden" name="type" value="opac" />
			<input type="hidden" name="marclist" value="" />
			<input type="hidden" name="and_or" value="and" />
			<input type="hidden" name="excluding" value="" />
			<input type="hidden" name="operator" value="contains" />
			<input type="text" size="12" name="value" id="value" />&nbsp;<input type="submit"  class="submit" name="Go" value="Search" /></form></div>
<div class="menu"><a href="/cgi-bin/koha/opac-user.pl">your library home</a> |   
	<a href="/cgi-bin/koha/opac-account.pl">your account</a>  | 
	<a href="/cgi-bin/koha/opac-userdetails.pl">your personal details</a> | <a class="logout" href="/cgi-bin/koha/opac-logout.pl">log out</a>
  </ul>
</div>
</div>