<div id="nav"><ul><!-- Display for NPL //<li><a href="http://www.athenscounty.lib.oh.us/index.html">home</a></li>

  <li><a href="http://www.athenscounty.lib.oh.us/library.html">your library</a></li>
  <li><a href="http://www.athenscounty.lib.oh.us/readers/index.asp">reader's connection</a></li>
    <li><a href="http://www.athenscounty.lib.oh.us/kids/index.asp">kids' page</a></li>
    <li><a href="http://www.athenscounty.lib.oh.us/teens/index.asp">teens</a></li> //Display for NPL -->
  <li><a href="/cgi-bin/koha/opac-main.pl">library catalog</a>
  	<ul>
		<li><a href="/cgi-bin/koha/opac-search.pl">Advanced Search</a></li>
		<!-- Display for NPL //
		<li><a href="/opac-format-search.php">Search by Format and Date</a></li>
		<li><a href="http://66.213.78.70/upcoming.cfm">Upcoming Releases Waiting List</a></li> //Display for NPL -->
</ul>
	<!-- TMPL_IF NAME="loggedinusername" -->
	<ul>
		<li><a href="/cgi-bin/koha/opac-suggestions.pl">Suggestions</a></li>
	</ul>
	<!-- /TMPL_IF -->
  </li>
 <!-- Display for NPL // <li><a href="http://www.athenscounty.lib.oh.us/programs.asp">programs</a></li>

  <li><a href="http://www.athenscounty.lib.oh.us/branch.html">branches</a></li>
  <li><a href="http://www.athenscounty.lib.oh.us/mobile.asp">the bookmobile</a></li>
  <li><a href="http://www.oplin.org">OPLIN</a></li>
  <li><a href="http://www.athenscounty.lib.oh.us/contact.html">contact the library</a></li> //Display for NPL -->
  </ul>
</div>