<div id="nav"><ul><li><a href="http://www.athenscounty.lib.oh.us/index.html">home</a></li>

  <li><a href="http://www.athenscounty.lib.oh.us/library.html">your library</a></li>
  <li><a href="http://www.athenscounty.lib.oh.us/readers/index.asp">reader's connection</a></li>
    <li><a href="http://www.athenscounty.lib.oh.us/kids/index.asp">kids' page</a></li>
    <li><a href="http://www.athenscounty.lib.oh.us/teens/index.asp">teens</a></li>
  <li><a href="/cgi-bin/koha/opac-main.pl">library catalog</a>
  	<ul>
		<li><a href="/cgi-bin/koha/opac-search.pl">Advanced Search</a></li>
		<li><a href="/cgi-bin/koha/opac-user.pl">Your Account</a></li>
		<li><a href="http://66.213.78.70/upcoming.cfm">Upcoming Releases Waiting List</a></li>
	</ul>
  </li>
  <li><a href="http://www.athenscounty.lib.oh.us/programs.asp">programs</a></li>

  <li><a href="http://www.athenscounty.lib.oh.us/branch.html">branches</a></li>
  <li><a href="http://www.athenscounty.lib.oh.us/mobile.asp">the bookmobile</a></li>
  <li><a href="http://www.oplin.org">OPLIN</a></li>
  <li><a href="http://www.athenscounty.lib.oh.us/contact.html">contact the library</a></li>
  </ul>
</div>