<br clear=all>
<p> &nbsp; </p>


</BLOCKQUOTE>

<CENTER>
<FONT SIZE=2>
<A HREF="/cgi-bin/koha/mainpage.pl">返回主頁</a> ||
<A HREF="/cgi-bin/koha/loadmodules.pl?module=search&type=intranet">館藏查詢</a> ||
<A HREF="/cgi-bin/koha/members-home.pl">讀者帳戶</a> ||
<A HREF="/cgi-bin/koha/loadmodules.pl?module=acquisitions">書藉購置</a> ||
<A HREF="/cgi-bin/koha/circ/circulation.pl">流通服務</a> ||
<A HREF="/cgi-bin/koha/reports-home.pl">報表列印</a> ||
<A HREF="/cgi-bin/koha/admin-home.pl">系統參數</a> ||
<A HREF="/cgi-bin/koha/about.pl">關於<span lang=mi>Koha</span></a> || 
線上說明
</FONT>
</CENTER>
</BODY>

</HTML>
