<!-- saas@users.sf.net 21-APR-2002 renamed "aquisitions" to "acquisitions" -->

<br clear=all>
<p> &nbsp; </p>

</BLOCKQUOTE>

<table cellpadding=0 cellspacing=0 width="100%" border=0>
<TR VALIGN=TOP BGCOLOR="000000"><TD  COLSPAN=6><img src="/images/blackdot.gif"  WIDTH=1  HEIGHT=2  HSPACE=0 vspace=0></TD></TR></TABLE>

<CENTER>
<FONT SIZE=2  face="arial, helvetica">
<A HREF="/cgi-bin/koha/mainpage.pl">返回主頁</a> ||
<A HREF="/cgi-bin/koha/circ/circulation.pl">流通服務</a> ||
<A HREF="/cgi-bin/koha/catalogue-home.pl">館藏查詢</a> ||
<A HREF="/cgi-bin/koha/members-home.pl">讀者帳戶</a> ||
<A HREF="/cgi-bin/koha/loadmodules.pl?module=acquisitions">書藉購置</a> ||
<A HREF="/reports/">報表列印</a> ||
<A HREF="/cgi-bin/koha/admin-home.pl">系統設定</a> ||
<A HREF="/help/">使用說明</a>
</FONT>
</CENTER>
</BODY>

</HTML>

