<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<!--Authored by rachel@katipo.co.nz 104:38 1/11/99-->
<!--updated by rachel@katipo.co.nz 01:02 5/11/99-->

<html>
<head>
<title>KOHA: INTRANET: Issues & Returns</title>
<meta http-equiv="Content-Type" content="text/html; charset=big5">

</head>
<body text="black" bgcolor="white" link="#0000ff" vlink="#0000ff" "3366cc" Alink="#cc3300"
marginheight=0 marginwidth=0 leftmargin=0 topmargin=0 >



<!--HDL Colours

	Yellow = ffcc00 
	light blue = ccccff
	bright blue links = 0000ff
	aubergine = 663266 
	light green/grey = cccc99


-->

<!------------------------MENUS-------------------------------->

<table cellpadding=0 cellspacing=0 width="100%" border=0>
<tr valign=top bgcolor=ffcc00  >

	<td COLSPAN=3>
	<table cellpadding=0 cellspacing=0  border=0 height=29>
	<tr valign=top bgcolor=ffcc00  >
	<td background="/images/issues-spot-1.gif" width="224" 
	height="29"><font size=1 face="arial"><img src="/images/holder.gif" width=210 height=4 alt=" " hspace=0 vspace=0><br>
	<img src="/images/holder.gif" 
	width=35 height=21 align=left alt=" " hspace=0 vspace=0>KOHA: <A HREF="/cgi-bin/koha/mainpage.pl">HDL INTRANET</A><br>
	<img src="/images/holder.gif" width=210 height=1 alt=" " hspace=0 vspace=0></FONT></td>
	
	</TR></TABLE></TD>

<TD COLSPAN=3 align=right><font size=1 face="arial" color="white">I 1 &nbsp; &nbsp; </font></TD>


</tr>


<TR VALIGN=TOP BGCOLOR="ffcc00"><TD  COLSPAN=6><img src="/images/holder.gif"  WIDTH=1  HEIGHT=12  HSPACE=0 vspace=0></TD></TR>



<tr valign=top bgcolor=ffcc00  >

<TD><img src="/images/holder.gif" 
	width=35 height=21 align=left alt=" " hspace=0 vspace=0></TD>
<td>
<font size=2>
<form action=/cgi-bin/simple-redirect.pl method=post>
<select>

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=57>ISSUES & RETURNS
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-) Issues
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Reports

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - -  Issues Today			
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - -  Issues This Week
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - -  Issues This Month		

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>->  Returns
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Reports

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Returns Today			
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Returns This Week
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Returns This Month	


<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>->  Renewals
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Reports
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Renewals Today
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Renewals This Week
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Renewals This Month



<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>->  Overdue Books
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Overdue Today
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Money Recieved
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Today
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - This Week
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - This Month
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - This Year

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>->  Lost Books
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Reports
	
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Lost This Month
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Lost This year

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>->  Advanced Reports
</select>
</form>
</TD>
<TD>

<font size=2>

<form name=choose2>
<select name=dest size=1 onChange="leapto(this.form)">

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=57>CATALOGUE
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-> Search

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-> Full Add New

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>->  Bibliography
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Add

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Modify		
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Delete
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Reports
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Changes this week
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Changes this month
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Changes this year

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>->  Items
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Add

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Modify		
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Delete
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Reports
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Changes this week
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Changes this month
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Changes this year

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-> Stock Reports
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Levin
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Books	
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Talking Books
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Videos	
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp;
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Shanon
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Books	
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Talking Books
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Videos	
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp;
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Foxton
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Books	
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Talking Books
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Videos	
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------


<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>->  Advanced Reports
</select>
</form>
</TD>
<TD>

<font size=2>

<form name=choose2>
<select name=dest size=1 onChange="leapto(this.form)">

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=57>AQUISITIONS
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-> Orders
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Order Books
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Order Serials
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Order Other	
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Cancel Order
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Reports
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Ordered This Week
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Ordered This Month		
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Ordered This year	
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>->  Suppliers
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Supplier Details
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - On Order with Supplier
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Supplier Resources

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Amazon.com			
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Whitcoulls CD
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Whitcoulls Website	

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>->  Deliveries
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Accept Delivery
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Reports
	
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Delivered This Month
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Delivered This year
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>->  Budget
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Book Budget 1
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - This Month
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Year to Date
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; 
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Book Budget 2
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - This Month
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Year to Date

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; 
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Book Budget 4
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - This Month
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Year to Date

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; 
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Book Budget 5
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - This Month
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Year to Date

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; 
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Total Budget
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - This Month
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Year to Date
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; 
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - End Of Year Reports
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; 
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Next Years Commitment


<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>->  Advanced Reports
</select>
</form>

</TD>
<TD>
<font size=2>

<form name=choose2>
<select name=dest size=1 onChange="leapto(this.form)">

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=57>BORROWERS
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-> New Borrower
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Setup
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Check if Expired
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Policy
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Reports

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Total Borrowers			
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - New This Week
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - New This Month		
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - New This Year		

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>->  Borrower Enquirey
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - All Books Out
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Overdues
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - History
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Messages
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Reports
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Average Borrowings		<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Total Borrowings

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>->  Advanced Reports
</select>
</form>
</TD>
<TD>
<font size=2>
<form name=choose2>
<select name=dest size=1 onChange="leapto(this.form)">

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=57>OTHER
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-> OPAC
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Catalogue Search

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Renew Books		
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Member Details
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - - Update Details		

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-> Resources
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Fundview CD

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43> ->  Library Website

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43> ->  End of Year
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Stocktake
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Set New Budgets
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Audit Reports
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>-----------------------------------
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43> ->  Help
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Telnet Help
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Intranet Help
<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43>&nbsp; &nbsp; - Searching Help

<option value=/cgi-bin/tododisplay.pl?user=Rachel&todo=43> ->  Advanced Reports
</select>
</form>
</td>
</tr>

<tr valign=top bgcolor=ffcc00 >
<TD COLSPAN=4>&nbsp;</TD>
	<td  ALIGN=RIGHT COLSPAN=2 >
	<table cellpadding=0 cellspacing=0  border=0 height=29>

<tr valign=top bgcolor=ffcc00 >
	<td background="/images/issues-spot-2.gif" width="235" 
	height="29"  ALIGN=RIGHT ><font size=1 face="arial"><img src="/images/holder.gif" width=223 height=12 alt=" " hspace=0 vspace=0><br>
	<img src="/images/holder.gif" 
	width=26 height=17 align=right alt=" " hspace=0 vspace=0>you are in <A HREF="index.html">ISSUES & RETURNS</a><br>
	<img src="/images/holder.gif" width=223 height=1 alt=" " hspace=0 vspace=0></FONT></td>
	
	</TR></TABLE></TD>




</tr>
<TR VALIGN=TOP BGCOLOR="000000"><TD  COLSPAN=6><img src="/images
/blackdot.gif"  WIDTH=1  HEIGHT=2  HSPACE=0 vspace=0></TD></TR>

</table>
<BLOCKQUOTE>
