<br clear=all>
<p> &nbsp; </p>


</BLOCKQUOTE>

<CENTER>
<FONT SIZE=2  face="arial, helvetica">
<A HREF="/cgi-bin/koha/mainpage.pl">主頁</a> ||
<A HREF="/cgi-bin/koha/loadmodules.pl?module=search&type=intranet">目錄</a> ||
<A HREF="/cgi-bin/koha/members-home.pl">讀者</a> ||
<A HREF="/cgi-bin/koha/loadmodules.pl?module=acquisitions">購置</a> ||
<A HREF="/cgi-bin/koha/circ/circulation.pl">流通</a> ||
<A HREF="/cgi-bin/koha/reports-home.pl">報表</a> ||
<A HREF="/cgi-bin/koha/admin-home.pl">設定</a> ||
<A HREF="/cgi-bin/koha/about.pl">關於</a> || 
線上說明
</FONT>
</CENTER>
</BODY>

</HTML>
