<br clear=all>
<p> &nbsp; </p>


</BLOCKQUOTE>

<CENTER>
<FONT SIZE=2  face="arial, helvetica">
<A HREF="/cgi-bin/koha/mainpage.pl">返回主頁</a> ||
<A HREF="/cgi-bin/koha/loadmodules.pl?module=search&type=intranet">館藏查詢</a> ||
<A HREF="/cgi-bin/koha/members-home.pl">讀者帳戶</a> ||
<A HREF="/cgi-bin/koha/loadmodules.pl?module=acquisitions">書藉購置</a> ||
<A HREF="/cgi-bin/koha/circ/circulation.pl">流通服務</a> ||
<A HREF="/cgi-bin/koha/reports-home.pl">報表列印</a> ||
<A HREF="/cgi-bin/koha/admin-home.pl">系統參數</a> ||
<A HREF="/cgi-bin/koha/about.pl">有關<mi>Koha</mi></a> || 
Help
</FONT>
</CENTER>
</BODY>

</HTML>
