<!--
 list of Classes to be included in /catalogue/index.html and cat/index.html
 This is a qick-fix - These should really be fetched from the database
-->
<option value="E">Facile/livres d'images
<option value="ER">Lecteur débutant	
<option value="JNF">Junior Hors fiction
<option value="JF">Junior Fiction
<option value="TREF">Référence du professeur
<option value="FYA">Fiction Jeune Adulte	
<option value="REF">Ouvrages de référence
<option value="F">Fiction
<option value="NF">Non-Fiction
<option value="CD">CD
<!--	<option value="E|ER">Easy Books-->

