#!/usr/bin/perl

# Copyright 2014 ByWater Solutions
#
# This file is part of Koha.
#
# Koha is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Koha is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Koha; if not, see <http://www.gnu.org/licenses>.
#

use Modern::Perl;

use CGI;
use JSON qw(to_json);

use C4::Auth qw(check_cookie_auth);

use Koha::Club::Templates;

my $cgi = CGI->new;

my ($auth_status) = check_cookie_auth( $cgi->cookie('CGISESSID'), { clubs => 'edit_templates' } );
if ( $auth_status ne "ok" ) {
    exit 0;
}

my $success = 0;

my $op = $cgi->param('op') || q{};
my $id = $cgi->param('id');

my $club_template = Koha::Club::Templates->find($id);
if ( $club_template && $op eq 'cud-delete' ) {
    $success = $club_template->delete();
}

binmode STDOUT, ':encoding(UTF-8)';
print $cgi->header( -type => 'application/json', -charset => 'UTF-8' );

print to_json( { success => $success ? 1 : 0 } );
