#!/bin/sh

set -e

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/postrm.mysql
    dbc_go koha $@
fi

if [ "$1" = "purge" ]; then
    configfile="/etc/koha/koha-conf.xml"
    rm -f "$configfile"
    if which ucf >/dev/null 2>&1; then
        ucf --purge "$configfile"
    fi

    rm -rf /var/log/koha
fi

#DEBHELPER#
