TRUNCATE systempreferences;
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('template', 'default', 'Preference order for intranet interface templates', NULL, 'Themes');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('autoBarcode', '0', 'Barcode is auto-calculated', NULL, 'YesNo');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('acquisitions', 'normal', 'Normal, budget-based acquisitions, or Simple bibliographic-data acquisitions', 'simple|normal', 'Choice');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('autoMemberNum', '0', 'Member number is auto-calculated', NULL, 'YesNo');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('authoritysep', '--', 'the separator used in authority/thesaurus. Usually --', '10', 'free');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('opaclanguages', 'fr', 'Set the preferred order for translations.  The top language will be tried first.', NULL, 'Languages');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('opacthemes', 'css', 'Set the preferred order for themes.  The top theme will be tried first.', NULL, 'Themes');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('timeout', '120000000', 'Inactivity timeout for cookies authentication (in seconds)', NULL, 'Integer');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('marc', 'ON', 'Turn on MARC support', NULL, 'YesNo');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('marcflavour', 'UNIMARC', 'your MARC flavor (MARC21 or UNIMARC) used for character encoding', 'MARC21|UNIMARC', 'Choice');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('checkdigit', 'none', 'Validity checks on membership number: none or "Katipo" style checks', 'none|katipo', 'Choice');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('dateformat', 'metric', 'date format (us mm/dd/yyyy, metric dd/mm/yyy, ISO yyyy/mm/dd)', 'metric|us|iso', 'Choice');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('insecure', 'no', 'If YES, no auth at all is needed. Be careful if you set this to yes!', NULL, 'YesNo');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('maxoutstanding', '5', 'maximum amount withstanding to be able make reserves', NULL, 'Integer');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('maxreserves', '5', 'maximum number of reserves a member can make', NULL, 'Integer');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('noissuescharge', '5', 'maximum amount withstanding to be able to check out an item', NULL, 'Integer');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('KohaAdminEmailAddress', 'your.mail@here', 'the email address where borrowers modifs are sent', NULL, 'free');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('gist', '0.196', 'the gist rate. NOT in %, but in numeric form (0.12 for 12%)', NULL, 'free');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('LibraryName', '<b>Bienvenue dans Koha</b>', 'Library name as shown on main opac page', NULL, '');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('ldapserver', '', 'your ldap server', NULL, 'free');
INSERT INTO systempreferences (variable, value, explanation, options, type) VALUES ('ldapinfos', '', 'ldap info. The ldap will be used in dn : uid=xxx, <ldapinfos>', NULL, 'free');