#!/usr/bin/perl

# Copyright 2014 Vaara-kirjastot
# Copyright 2017 Koha-Suomi Oy
#
# This file is part of Koha
#
# Koha is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# Koha is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with Koha; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

use Modern::Perl;
binmode STDOUT, ":encoding(UTF-8)";

use CGI;
use JSON qw( to_json );

use Koha::Patrons;

my $input = new CGI;

my $othernames = $input->param('othernames');
my $borrowernumber = $input->param('borrowernumber');

my $response = {};

my $borrowernumber_who_has_this_othernames;
my $patron_who_has_this_othernames = Koha::Patrons->search({
    othernames     => $othernames,
    borrowernumber => { '!=' => $borrowernumber },
})->next;

if ($patron_who_has_this_othernames) {
    $borrowernumber_who_has_this_othernames =
        $patron_who_has_this_othernames->borrowernumber;
    $response->{borrowernumber} = $borrowernumber_who_has_this_othernames;
}

print $input->header(
    -type => 'text/json',
    -charset => 'UTF-8'
);

print to_json( $response );
