
INSERT INTO `auth_types` VALUES ('','Default','',''),('PNAME','PERSONAL NAME','100',''),('GNAME','GEOGRAPHIC NAME','151',''),('MNAME','MEETING NAME','111',''),('CNAME','CORPORATE NAME','110',''),('GENRE','GENRE/FORM TERMS','155',''),('TITLE','UNIFORM TITLES','130',''),('TTERM','TOPICAL TERMS','150',''),('CTERM','CHRONOLOGICAL TERMS','148','');
