<!--
 list of Classes to be included in /catalogue/index.html and cat/index.html
 This is a qick-fix - These should really be fetched from the database
-->
<option value="E">Easy / Picture Books
<option value="ER">Easy Reader	
<option value="JNF">Junior Non-Fiction
<option value="JF">Junior Fiction
<option value="TREF">Teacher Reference
<option value="FYA">Young Adult Fiction	
<option value="REF">Reference Books
<option value="F">Fiction
<option value="NF">Non-Fiction
<option value="CD">Compact Disc
<!--	<option value="E|ER">Easy Books-->

