apt-get install  \
apache2  \
apache2-mpm-worker  \
at  \
bzip2 \
daemon  \
gcc  \
gettext  \
idzebra-2.0-common \
idzebra-2.0-doc \
idzebra-2.0 \
idzebra-2.0-utils \
libalgorithm-checkdigits-perl \
libbiblio-endnotestyle-perl \
libbusiness-isbn-perl \
libcgi-session-perl \
libcgi-session-serialize-yaml-perl \
libclass-accessor-perl \
libclass-factory-util-perl \
libdata-ical-perl \
libdate-calc-perl \
libdate-ical-perl \
libdate-manip-perl  \
libdatetime-format-mail-perl  \
libdatetime-format-strptime-perl \
libdatetime-format-w3cdtf-perl \
libdatetime-locale-perl \
libdatetime-perl \
libdatetime-timezone-perl \
libdbd-mysql-perl \
libdbd-sqlite2-perl \
libdbi-perl \
libdigest-sha-perl \
libemail-date-perl \
libgcrypt11-dev  \
libgcrypt11  \
libgd2-xpm-dev  \
libgd-barcode-perl \
libgd-gd2-perl \
libhtml-scrubber-perl \
libhtml-template-pro-perl  \
libidzebra-2.0-dev \
libidzebra-2.0 \
libidzebra-2.0-mod-alvis \
libidzebra-2.0-mod-grs-marc \
libidzebra-2.0-mod-grs-regx \
libidzebra-2.0-mod-grs-xml \
libidzebra-2.0-mod-text \
libidzebra-2.0-modules \
libgraphics-magick-perl  \
libjson-perl \
libjson-xs-perl \
liblingua-ispell-perl \
liblingua-stem-perl \
liblist-moreutils-perl \
liblocale-gettext-perl \
liblocale-po-perl \
libmail-sendmail-perl \
libmarc-charset-perl \
libmarc-crosswalk-dublincore-perl \
libmarc-record-perl \
libmarc-xml-perl \
libmime-lite-perl \
libmodule-install-perl \
libmysqlclient15-dev  \
libnet-ldap-perl \
libnet-z3950-zoom-perl \
libnet-server-perl \
libnumber-format-perl \
libpdf-api2-perl \
libpdf-reuse-barcode-perl \
libpdf-reuse-perl \
libpdf-table-perl \
libpoe-perl \
libschedule-at-perl \
libtemplate-perl \
libtext-charwidth-perl \
libtext-csv-perl \
libtext-iconv-perl \
libtext-wrapi18n-perl \
libtimedate-perl \
libtime-duration-perl \
libtime-format-perl \
libunix-syslog-perl \
libxml2-dev \
libxml2 \
libxml2-utils \
libxml-dom-perl \
libxml-dumper-perl \
libxml-libxml-perl \
libxml-libxslt-perl \
libxml-namespacesupport-perl \
libxml-parser-perl \
libxml-perl \
libxml-regexp-perl \
libxml-rss-perl \
libxml-sax-writer-perl   \
libxml-simple-perl  \
libxml-xslt-perl \
libxslt1.1 \
libxslt1-dev \
libyaml-perl \
libyaml-syck-perl  \
libyaz-dev \
libyaz3 \
make  \
mysql-server  \
yaz-doc \
yaz
