<!doctype html public "-//w3c//dtd html 4.0 transitional//de">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-2">

<!--Authored by rachel@katipo.co.nz 10:46 24/12/99-->
<!-- opac-top.inc, translation by dnmeid, based on 1.5 -->

<html>
<head>
<title>KOHA: OPAC Katalogsuche</title>

</head>
<body text="black" bgcolor="white" link="#0000ff" vlink="#3366cc" Alink="#cc3300"
marginheight=0 marginwidth=0 leftmargin=0 topmargin=0 >



<!--HDL Colours

        Yellow = ffcc00
        light blue = ccccff
        bright blue links = 0000ff
        aubergine = 663266
        light green/grey = cccc99


-->

<!------------------------MENUS-------------------------------->

<table cellpadding=0 cellspacing=0 width="100%" border=0>
	<tr BGCOLOR="#339999" >

  	<td valign=bottom>
  		<img src="/default/de/images/inside-top-search.gif"
				width=349 height=50 alt="KOHA: Katalogsuche" hspace=0 vspace=0 border=0>
		</td>

		<td align=right>
			<a href="/cgi-bin/koha/opac-search.pl"
				onMouseOver="document.mouseover.src='/default/de/images/mouseover-search.gif'"
				onMouseOut="document.mouseover.src='/default/all/images/holder.gif'">
				<img src="/default/de/images/menu-search.gif"
				width=71 height=30 alt="Suche" hspace=0 vspace=0 border=0 name="menu-search">
			</a>

<!--	<a href="/members/"
				onMouseOver="document.mouseover.src='/default/de/images/mouseover-member.gif'"
				onMouseOut="document.mouseover.src='/default/all/images/holder.gif'">
				<img src="/default/de/images/menu-login.gif"
				width=111 height=30 alt="Mitgliederbereich" hspace=0 vspace=0 border=0 name="menu-login">
			</a>
-->
			<a href="/join.html"
				onMouseOver="document.mouseover.src='/default/de/images/mouseover-join.gif'"
				onMouseOut="document.mouseover.src='/default/all/images/holder.gif'">
				<img src="/default/de/images/menu-join.gif"
				width=54 height=30 alt="Beitreten" hspace=0 vspace=0 border=0 name="menu-join">
			</a>

			<a href="/cgi-bin/koha/opac-main.pl"
				onMouseOver="document.mouseover.src='/default/de/images/mouseover-home.gif'"
				onMouseOut="document.mouseover.src='/default/de/images/holder.gif'">
				<img src="<TMPL_VAR NAME='themelang'>/images/menu-home.gif"
				width=60 height=30 alt="Start" hspace=0 vspace=0 border=0 name="menu-home">
			</a>
		</td>

  </TR>

	<tr valign=top>

    <td>
     	<img src="/default/all/images/inside-koha-bottom.gif"
				width=69 height=44 alt="KOHA" hspace=0 vspace=0 border=0 >
		</td>

    <td align=right>
    	<img src="/default/all/images/holder.gif"
				width=300 height=48 alt="" hspace=0 vspace=0 name="mouseover" >
		</td>

  </TR>

</TABLE>



<!-------------------------MAIN BODY OF PAGE-------------------------->
<BLOCKQUOTE>
