#!/usr/bin/perl

# Copyright 2016 BibLibre Morgane Alonso
#
# This file is part of Koha.
#
# Koha is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Koha is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Koha; if not, see <https://www.gnu.org/licenses>.
#

use Modern::Perl;

use Koha::SharedContent;
use Koha::Subscription;
use C4::Auth   qw(get_template_and_user);
use C4::Output qw( output_html_with_http_headers );

use CGI;

my $input = CGI->new;

my $templatename;
if ( $input->param("resource") eq 'report' ) {
    $templatename = "mana/mana-report-search-result.tt";
} else {
    $templatename = "mana/mana-subscription-search-result.tt";
}

my ( $template, $loggedinuser, $cookie ) = get_template_and_user(
    {
        template_name => $templatename,
        query         => $input,
        type          => "intranet",

        # flagsrequired   => { serials => $permission },
        flagsrequired => { serials => 'create_subscription' },
        debug         => 1,
    }
);

my ( $identifier, $sub_mana_info );
$identifier = $input->param('id');
$template->param( lowWarned => 5, warned => 10, highWarned => 20 );
my $package = "Koha::" . ucfirst( $input->param('resource') );
$sub_mana_info = $package->get_search_info($identifier);

$sub_mana_info->{usecomments} = $input->param('usecomments');
my $resourcename = $input->param('resource');
my $result       = Koha::SharedContent::search_entities( $resourcename, $sub_mana_info );
my $nbofcomment;
foreach my $resource ( @{ $result->{data} } ) {
    $nbofcomment = 0;
    foreach my $comment ( @{ $resource->{comments} } ) {
        $nbofcomment += $comment->{nb};
    }
    $resource->{nbofcomment} = $nbofcomment;
}

$template->param( $input->param('resource') . "s" => $result->{data} );
$template->param( statuscode                      => $result->{code} );
$template->param( msg                             => $result->{msg} );

output_html_with_http_headers $input, $cookie, $template->output;
