#!/usr/bin/perl

# Copyright 2016 BibLibre Baptiste Wojtkowski
#
# This file is part of Koha.
#
# Koha is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Koha is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Koha; if not, see <http://www.gnu.org/licenses>.
#


use Modern::Perl;

use Koha::SharedContent;
use C4::Auth qw(check_cookie_auth);

use CGI;
use JSON;

my $input = new CGI;
binmode STDOUT, ":encoding(UTF-8)";
print $input->header( -type => 'text/plain', -charset => 'UTF-8' );

my ( $auth_status, $sessionID ) =
  check_cookie_auth( $input->cookie('CGISESSID'),
    { serials => 'create_subscription' } );

if ( $auth_status ne "ok" ) {
    exit 0;
}

my $mana_ip = C4::Context->config('mana_config');

my $url = "$mana_ip/getsecuritytoken";
my $request = HTTP::Request->new( POST => $url );

my $content;
$content->{ firstname }= $input->param("firstname");
$content->{ lastname }= $input->param("lastname");
$content->{ email }= $input->param("email");
my $json = to_json( $content, { utf8 => 1 } );
$request->content($json);
my $result = Koha::SharedContent::process_request($request);

print(to_json($result));
