</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="<!-- TMPL_VAR NAME="themelang" -->/includes/favicon.ico" type="image/x-icon" />
<meta http-equiv="Content-Language" content="en-us" />
<style type="text/css"> 
    @import url(<!-- TMPL_VAR NAME="themelang" -->/css/print.css);
</style>
<script type="text/javascript" language="javascript" src="<!-- TMPL_VAR NAME="themelang" -->/js/script.js"></script>
<script type="text/javascript" language="javascript" src="<!-- TMPL_VAR NAME="themelang" -->/js/basket.js"></script>
    <script type="text/javascript" language="javascript">
        var MSG_NO_RECORD_SELECTED = "No biblio selected";
        var MSG_NO_RECORD_ADDED = "No biblio added";
        var MSG_CONFIRM_DEL_BASKET = "Are you sure you want to empty your book bag?"
        var MSG_CONFIRM_DEL_RECORDS = "Are you sure you want to remove the selected items?";
    </script>