<div id="masthead">

<h1><!-- TMPL_IF NAME="opacsmallimage" --><img alt="<!-- TMPL_VAR NAME="LibraryName" -->" src="<!-- TMPL_VAR NAME="opacsmallimage" -->" /><!-- /TMPL_IF -->Library Catalog Search</h1>

<ul><li><a href="/cgi-bin/koha/opac-main.pl">Search Home</a></li>
<li><a href="/cgi-bin/koha/opac-search.pl">Advanced Search</a></li><li><a href="/cgi-bin/koha/opac-basket.pl" onclick="openBasket(); return false;" title="A &quot;shopping cart&quot; for your selections">Book Bag<span id="basket"><script language="javascript" type="text/javascript">if(basketcount){ document.write(basketcount) };</script></span></a></li></ul>

</div>
