#!/usr/bin/perl

# This file is part of Koha.
#
# Copyright 2017 Aleisha Amohia <aleisha@catalyst.net.nz>
#
# Koha is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Koha is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Koha; if not, see <http://www.gnu.org/licenses>.

use Modern::Perl;

use JSON qw( to_json );
use CGI;
use C4::Auth   qw ( check_cookie_auth );
use C4::Output qw( is_ajax output_with_http_headers );
use Koha::Checkouts;

=head1 NAME

svc/checkout_notes - Web service for managing patron notes set on issues

=head1 DESCRIPTION

=cut

# AJAX requests
my $is_ajax       = is_ajax();
my $query         = CGI->new;
my ($auth_status) = check_cookie_auth( $query->cookie('CGISESSID'), { circulate => 'manage_checkout_notes' } );
if ( $auth_status ne "ok" ) {
    exit 0;
}
my $op = $query->param('op');
if ($is_ajax) {
    my $issue_id = $query->param('issue_id');
    my $issue    = Koha::Checkouts->find($issue_id);
    if ( $op eq 'cud-seen' ) {
        $issue->set( { noteseen => 1 } )->store;
    } elsif ( $op eq 'cud-notseen' ) {
        $issue->set( { noteseen => 0 } )->store;
    }
    my $json = to_json( { seen => $issue->noteseen } );
    output_with_http_headers $query, undef, $json, 'js';
    exit;
}
