#!/usr/bin/perl

# This file is part of Koha.
#
# Copyright 2017 Koha Development Team
#
# Koha is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Koha is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Koha; if not, see <http://www.gnu.org/licenses>.

use Modern::Perl;

use C4::Reports::Guided;
use Koha::Reports;
use C4::Auth qw( get_template_and_user get_session );
use C4::Output qw( output_html_with_http_headers );
use CGI qw ( -utf8 );

my $query  = CGI->new();
my $report_id = $query->param('report_id');

my ( $template, $loggedinuser, $cookie ) = get_template_and_user(
    {
        template_name   => "reports/convert_report.tt",
        query           => $query,
        type            => "intranet",
        flagsrequired   => { reports => 'execute_reports' },
    }
);

my $report = Koha::Reports->find( $report_id );

my $params;
if ( $report ) {
    my $sql = $report->savedsql;
    my $updated_sql = C4::Reports::Guided::convert_sql( $sql );
    $params = { msg => 'can_be_updated', updated_sql => $updated_sql, current_sql => $sql };
} else {
    $params = { msg => 'no_report' };
}

$template->param( %$params );

output_html_with_http_headers $query, $cookie, $template->output;
