INSERT INTO `authorised_values` (category, authorised_value, lib) VALUES ('ITEMLOST','0','Available'),
INSERT INTO `authorised_values`  (category, authorised_value, lib) VALUES ('ITEMLOST','2','Long Overdue (Lost)'),
INSERT INTO `authorised_values` (category, authorised_value, lib) VALUES ('ITEMLOST','1','Lost'),
INSERT INTO `authorised_values`  (category, authorised_value, lib ) VALUES ('ITEMLOST','3','Lost and Paid For'),
INSERT INTO `authorised_values`  (category, authorised_value, lib )VALUES ('ITEMLOST','4','Missing'),
INSERT INTO `authorised_values`  (category, authorised_value, lib) VALUES ('BINDING','0','NOT Damaged'),
INSERT INTO `authorised_values` (category, authorised_value, lib) VALUES ('BINDING','1','Damaged'),
INSERT INTO `authorised_values` (category, authorised_value, lib) VALUES ('NOTFORLOAN','-1','Ordered'),
INSERT INTO `authorised_values` (category, authorised_value, lib) VALUES ('NOTFORLOAN','0','For Loan'),
INSERT INTO `authorised_values` (category, authorised_value, lib) VALUES ('NOTFORLOAN','1','Not For Loan'),
INSERT INTO `authorised_values` (category, authorised_value, lib) VALUES ('NOTFORLOAN','2','Staff Collection'),
INSERT INTO `authorised_values` (category, authorised_value, lib) VALUES ('DPT','0','Reference'),
INSERT INTO `authorised_values` (category, authorised_value, lib) VALUES ('DPT','1','Stacks'),
INSERT INTO `authorised_values` (category, authorised_value, lib) VALUES ('DPT','2','Fiction'),
INSERT INTO `authorised_values` (category, authorised_value, lib) VALUES ('DPT','3','Biography'),
INSERT INTO `authorised_values` (category, authorised_value, lib) VALUES ('DPT','4','Media'),
