<!--
 list de Classes to be included dans /catalogue/index.html and cat/index.html
 This is a qick-fix - These should really be fetched from the database
-->
<option value="E">BD
<option value="ER">Lecture facile	
<option value="JNF">Junior NF
<option value="JF">Junior
<option value="TREF">Ref. prof.
<option value="FYA">Ado fiction	
<option value="REF">Références
<option value="F">Fiction
<option value="NF">NF
<option value="CD">CD
<!--	<option value="E|ER">Easy Books-->

