<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<!--Authored by rachel@katipo.co.nz 10:46 24/12/99-->

<html>
<head>
<title>KOHA: Rechercher dans le catalogue</title>

</head>
<body text="black" bgcolor="white" link="#0000ff" vlink="#3366cc" Alink="#cc3300"
marginheight=0 marginwidth=0 leftmargin=0 topmargin=0 >

<!--HDL Colours

        Yellow = ffcc00
        light blue = ccccff
        bright blue links = 0000ff
        aubergine = 663266
        light green/grey = cccc99


-->

<!------------------------MENUS-------------------------------->

<table cellpadding=0 cellspacing=0 border=0 width="40%">
<tr   bgcolor="#fecc99" >

<td align=right><a href="/cgi-bin/koha/opac-main.pl">Accueil</a>
<td align=right><a href="/cgi-bin/koha/opac-search.pl">Rechercher</a>
<td align=right><a href="/cgi-bin/koha/opac-user.pl">Votre compte lecteur</a>
        </TR>
</TABLE>
<br/><br/>
<!-------------------------MAIN BODY OF PAGE-------------------------->
