<br clear="all">
<p> &nbsp; </p>

<div class="center">
<a href="/cgi-bin/koha/mainpage.pl">На початок</a> ||
<a href="/cgi-bin/koha/loadmodules.pl?module=search&amp;type=intranet">Каталог</a> ||
<a href="/cgi-bin/koha/members/members-home.pl">Відвідувачі</a> ||
<a href="/cgi-bin/koha/loadmodules.pl?module=acquisitions">Надходження</a> ||
<a href="/cgi-bin/koha/circ/circulation.pl">Обіг</a> ||
<a href="/cgi-bin/koha/reports-home.pl">Звіти</a> ||
<a href="/cgi-bin/koha/admin-home.pl">Параметри</a> ||
<a href="/cgi-bin/koha/about.pl">Про систему</a> || 
Допомога
</div>

</body>
</html>