#!/bin/sh
# koha-foreach -- run a command for each Koha instance
# Copyright 2010  Catalyst IT, Ltd
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -e

listopts=""
while [ ! -z "$1" ]
do
    case "$1" in
        --email) listopts="$listopts --email";;
      --noemail) listopts="$listopts --noemail";;
      --enabled) listopts="$listopts --enabled";;
     --disabled) listopts="$listopts --disabled";;
          --sip) listopts="$listopts --sip";;
        --nosip) listopts="$listopts --nosip";;
        --plack) listopts="$listopts --plack";;
      --noplack) listopts="$listopts --noplack";;
  --letsencrypt) listopts="$listopts --letsencrypt" ;;
--noletsencrypt) listopts="$listopts --noletsencrypt" ;;
              *) break;;
    esac
    shift
done
            
for name in $(koha-list $listopts)
do
    cmd=`echo "$@" | sed -e s/__instancename__/${name}/g`
    (
    exec 3>&1
    sudo -u "$name-koha" \
    env PERL5LIB=/usr/share/koha/lib \
        KOHA_CONF="/etc/koha/sites/$name/koha-conf.xml" \
        ${cmd} 2>&1 >&3 | sed -e "s/^/$name: /" >&2 3>&-
    exec 3>&-
    ) | sed -e "s/^/$name: /"

done

