#!/bin/sh
#
# koha-stop-sip -- Stop SIP server for named Koha instance
# Copyright 2012  Catalyst IT, Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

for name in "$@"
do
    if [ ! -e /etc/koha/sites/${name}/koha-conf.xml ] ;
    then
        echo "No such instance: ${name}" > /dev/stderr
        continue;
    fi
    if [ ! -e /var/run/koha/${name}/${name}-koha-sip.pid ] ;
    then
        echo "SIP server for ${name} not running."
        continue;
    fi
    echo "Stopping SIP server for $name"
    KOHA_CONF=/etc/koha/sites/${name}/koha-conf.xml
    PERL5LIB=/usr/share/koha/lib
    export KOHA_CONF PERL5LIB
    daemon \
        --name="$name-koha-sip" \
        --errlog="/var/log/koha/$name/sip-error.log" \
        --stdout="/var/log/koha/$name/sip.log" \
        --output="/var/log/koha/$name/sip-output.log" \
        --verbose=1 \
        --respawn \
        --delay=30 \
        --pidfiles="/var/run/koha/${name}" \
        --user="$name-koha.$name-koha" \
        --stop \
        -- \
        perl \
        "/usr/share/koha/lib/C4/SIP/SIPServer.pm" \
        "/etc/koha/sites/${name}/SIPconfig.xml"
done
