#!/bin/sh
#
# koha-enable-sip -- Set up the config files to allow SIP to run
# Copyright 2012  Catalyst IT, Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

for name in "$@"
do
    if [ ! -e /etc/koha/sites/${name}/koha-conf.xml ] ;
    then
        echo "No such instance: ${name}" > /dev/stderr
        continue;
    fi
    sipfile=/etc/koha/sites/${name}/SIPconfig.xml
    if [ -e ${sipfile} ]
    then
        echo "SIP already enabled for $name"
    else
        echo "Enabling SIP for $name - edit ${sipfile} to configure"
        cp -v /etc/koha/SIPconfig.xml ${sipfile}
        chown ${name}-koha:${name}-koha ${sipfile}
        chmod 600 ${sipfile}
    fi
done
