#!/bin/sh
#
# koha-stop-zebra -- Stop Zebra for named Koha instandes
# Copyright 2010  Catalyst IT, Ltd
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

for name in "$@"
do
    echo "Stopping Zebra server for $name"
    daemon \
        --name="$name-koha-zebra" \
        --errlog="/var/log/koha/$name/zebra-error.log" \
        --stdout="/var/log/koha/$name/zebra.log" \
        --output="/var/log/koha/$name/zebra-output.log" \
        --verbose=1 \
        --respawn \
        --delay=30 \
        --user="$name-koha.$name-koha" \
        --stop \
        -- \
        zebrasrv \
        -f "/etc/koha/sites/$name/koha-conf.xml" || true
done
