#!/bin/sh
#
# koha-email-disable -- turn off the email for a Koha instance
# Copyright 2010  Catalyst IT, Ltd
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

if [ "$#" = 0 ]
then
    echo "Disables the email for a koha instance." 1>&2
    echo "Usage: $0 instancename..." 1>&2
    exit 1
fi
libdir=/var/lib/koha
for name in "$@"
do
    if [ ! -d $libdir/$name ]
    then 
        echo "$0: no koha instance \"$name\"" 1>&2
        continue
    fi
    rm -f $libdir/$name/email.enabled
done
