#!/bin/sh
#
# koha-reset-passwd -- reset password for a user in a Koha instance
# Copyright 2010  Catalyst IT, Ltd
# Copyright 2019  Theke Solutions
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


set -e

# include helper functions
if [ -f "/usr/share/koha/bin/koha-functions.sh" ]; then
    . "/usr/share/koha/bin/koha-functions.sh"
else
    echo "Error: /usr/share/koha/bin/koha-functions.sh not present." 1>&2
    exit 1
fi

usage()
{
    local scriptname=$0
    cat <<EOF
Resets the password for the specified user on the Koha instance.

Usage: $scriptname instancename userid

Note: The generated password will be printed.
EOF
}

set_password()
{
    local instancename=$1
    local userid=$2

    if sudo -u "$instancename-koha" -H \
        env PERL5LIB=$PERL5LIB \
        KOHA_CONF="/etc/koha/sites/$instancename/koha-conf.xml" \
        $KOHA_HOME/$KOHA_BINDIR/admin/set_password.pl --userid $userid ; then

        return 0
    else
        return 1
    fi
}

if [ $# -lt 2 ]; then
    usage
    die "Wrong parameters"
fi

instance="$1"
shift
# Adjust KOHA_HOME, KOHA_BINDIR if needed
adjust_paths_git_install $instance

for userid in "$@"
do
    set_password $instance $userid
done

exit 0
