#!/bin/sh
#
# koha-enable -- enable a Koha instance.
# Copyright 2010  Catalyst IT, Ltd
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -e

# include helper functions
if [ -f "/usr/share/koha/bin/koha-functions.sh" ]; then
    . "/usr/share/koha/bin/koha-functions.sh"
else
    echo "Error: /usr/share/koha/bin/koha-functions.sh not present." 1>&2
    exit 1
fi

enable_instance()
{
    local instancename=$1
    local instancefile="/etc/apache2/sites-available/$instancename.conf"

    if ! is_enabled $instancename; then
        sed -i 's:^\(\s*Include /etc/koha/apache-shared-disable.conf\)$:#\1:' \
            "$instancefile"
        return 0
    else
        return 1
    fi
}

usage()
{
    local scriptname=$0
    cat <<EOF
Enables Koha instances.

Usage: $scriptname instancename1 instancename2...

EOF
}

# Parse command line.
[ $# -ge 1 ] || ( usage ; die "Missing instance name..." )

restart_apache="no"

for name in "$@"
do
    if is_instance $name ; then
        if enable_instance $name; then
            restart_apache="yes"
        else
            warn "Instance $name already enabled."
        fi
    else
        warn "Unknown instance $name."
    fi
done

if [ "$restart_apache" = "yes" ]; then
    /etc/init.d/apache2 restart
fi

exit 0
