<br clear="all">
<p> &nbsp; </p>

<div class="center">
<a href="/cgi-bin/koha/mainpage.pl">Accueil</a> ||
<a href="/cgi-bin/koha/loadmodules.pl?module=search&amp;type=intranet">Catalogue</a> ||
<a href="/cgi-bin/koha/members/members-home.pl">Lecteurs</a> ||
<a href="/cgi-bin/koha/loadmodules.pl?module=acquisitions">Acquisitions</a> ||
<a href="/cgi-bin/koha/circ/circulation.pl">Prêt</a> ||
<a href="/cgi-bin/koha/reports-home.pl">Bilans</a> ||
<a href="/cgi-bin/koha/admin-home.pl">Paramètres</a> ||
<a href="/cgi-bin/koha/about.pl">A propos</a> || 
Aide
</div>

</body>
</html>