<script type="text/javascript">
//<![CDATA[
var MSG_ADDITEM_JS_ADDITEM = _("Add item");
var MSG_ADDITEM_JS_UPDATEITEM = _("Update item");
var MSG_ADDITEM_JS_EDIT = _("Edit");
var MSG_ADDITEM_JS_DELETE = _("Delete");
var MSG_ADDITEM_JS_CLEAR = _("Clear");
var MSG_ADDITEM_JS_CANT_RECEIVE_MORE_ITEMS = _("You can't receive any more items");
var MSG_ADDITEM_JS_IS_DUPLICATE = _("is duplicated");
var MSG_ADDITEM_JS_ALREADY_EXISTS_IN_DB = _("already exists in database");
//]]>
</script>
