<ul id="navigation">
    <li>    <a href="/cgi-bin/koha/cataloguing/addbiblio.pl?biblionumber=[% biblionumber %]">Edit bibliographic record</a></li>
	<li>    <a href="/cgi-bin/koha/catalogue/detail.pl?biblionumber=[% biblionumber %]">Normal view</a></li>
    <li>    <a href="/cgi-bin/koha/catalogue/MARCdetail.pl?biblionumber=[% biblionumber %]">View MARC in catalog</a></li>
    <li>    <a href="/cgi-bin/koha/catalogue/ISBDdetail.pl?biblionumber=[% biblionumber %]">View ISBD in catalog</a></li>
</ul>