<tfoot>
	<tr>
        <td colspan="9" style="text-align: right; font-weight:bold;">Totals:</td>
        <td>[% totaldue %]</td>
        <td>[% finetotal %]</td>
        <td>[% totalprice %]</td>
                <td colspan="3"><div class="date-select">
            <p><label for="newduedate">Renewal due date:</label> <input type="text" size="12" id="newduedate" name="newduedate" value="[% newduedate %]" readonly="readonly" />
</p>
            <p><label for="exemptfine">Forgive fines on return: <input type="checkbox" id="exemptfine" name="exemptfine" value="1" /></label></p></div>
		</td>
	</tr>
</tfoot>
