<div id="toolbar"><ul class="toolbar">
	<li><a href="/cgi-bin/koha/members/memberentry.pl?op=add&guarantorid=<!-- TMPL_VAR NAME="borrowernumber" -->&category_type=C">New</a></li>
	<li><a href="/cgi-bin/koha/members/memberentry.pl?borrowernumber=<!-- TMPL_VAR name="borrowernumber" -->&amp;modify=edit&amp;destination=circ&amp;categorycode=<!-- TMPL_VAR name="categorycode" -->">Edit</a></li>
	<li><a href="Someone please write this">Add Note</a></li>
	<li><a href="/cgi-bin/koha/members/member-password.pl?member=1">Change Password</a></li>
	<li><a href="">Print</a><ul><li><a href="">Page</a></li><li><a href="">Slip</a></li></ul></li>
	<li><a href="more">More</a><ul><li><a href="javascript:confirm_reregistration();">Renew Account</a></li>
	<li><a href="/cgi-bin/koha/members/member-flags.pl?member=1">Set Permissions</a></li>
	<li><a href="javascript:confirm_deletion();">Delete</a></li></ul></li>
	
</ul>
<br clear="all" /></div>