<script type="text/javascript">                            
    var GB_ROOT_DIR = "<!-- TMPL_VAR name="themelang" -->/lib/greybox/";                               
</script>
<script type="text/javascript" src="<!-- TMPL_VAR name="themelang" -->/lib/greybox/AJS.js"></script>
<script type="text/javascript" src="<!-- TMPL_VAR name="themelang" -->/lib/greybox/AJS_fx.js"></script>
<script type="text/javascript" src="<!-- TMPL_VAR name="themelang" -->/lib/greybox/gb_scripts.js"></script>
<link href="<!-- TMPL_VAR name="themelang" -->/lib/greybox/gb_styles.css" rel="stylesheet" type="text/css" />
