<script type="text/javascript">
    var GB_ROOT_DIR = "[% interface %]/[% theme %]/lib/greybox/";
</script>
<script type="text/javascript" src="[% interface %]/[% theme %]/lib/greybox/AJS.js"></script>
<script type="text/javascript" src="[% interface %]/[% theme %]/lib/greybox/AJS_fx.js"></script>
<script type="text/javascript" src="[% interface %]/[% theme %]/lib/greybox/gb_scripts.js"></script>
<link href="[% interface %]/[% theme %]/lib/greybox/gb_styles.css" rel="stylesheet" type="text/css" />
