<h5>Build and Run Reports</h5>
<ul>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Build new">Build New</a></li>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Used saved">Use Saved</a></li>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Create report from SQL">Create from SQL</a></li>
</ul>
<h5>Reports Dictionary</h5>
<ul>
<li><a href="/cgi-bin/koha/reports/dictionary.pl?phase=View Dictionary">View Dictionary</a></li>
</ul>