<div id="hold-group-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="hold-group-modal-label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="closebtn" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="hold-group-modal-label">Hold group</h4>
            </div>
            <div class="modal-body"> </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default deny" data-dismiss="modal">Close</button>
            </div> </div
        ><!-- /.modal-content --> </div
    ><!-- /.modal-dialog --> </div
><!-- /.modal -->
