<!-- Hold group modal -->
<div class="modal" id="hold-group-modal" tabindex="-1" role="dialog" aria-labelledby="hold-group-modal-label">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title" id="hold-group-modal-label">Hold group</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="Close"></button>
            </div>
            <div class="modal-body"> </div>
            <!-- /.modal-body -->
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
            </div>
            <!-- /.modal-footer --> </div
        ><!-- /.modal-content --> </div
    ><!-- /.modal-dialog --> </div
><!-- /.modal -->
