<div id="ArticleRequestsDisclaimerText_notes" class="hint customization_note"> This content will be shown to an OPAC user before they can place an article request. </div>

<div id="CatalogConcernHelp_notes" class="hint customization_note"> Include this content on the form shown in the OPAC when the user submits a catalog concern report. </div>

<div id="CatalogConcernTemplate_notes" class="hint customization_note"> Prefill the OPAC catalog concern form with this content as a template for the user's submission. </div>

<div id="CookieConsentBar_notes" class="hint customization_note"> Include this content in the cookie consent footer which is displayed in the OPAC when the CookieConsent system preference is enabled. </div>

<div id="CookieConsentPopup_notes" class="hint customization_note">
    Include this content in the popup message which is displayed in the OPAC when the CookieConsent system preference is enabled and the user clicks the "Your cookies" menu item in the header.
</div>

<div id="ILLModuleCopyrightClearance_notes" class="hint customization_note">
    Adding content to this region will enable the copyright clearance stage in request creation. The content will appear on the OPAC during the process of placing an ILL request.
</div>

<div id="IntranetmainUserblock_notes" class="hint customization_note"> Include this content in its own section on the main page of the staff interface </div>

<div id="StaffReportsHome_notes" class="hint customization_note"> Include this content in its own section on the reports home page</div>

<div id="opaccredits_notes" class="hint customization_note"> Include this content in the footer of all pages in the OPAC. </div>

<div id="OpacCustomSearch_notes" class="hint customization_note"> Replace the search box at the top of OPAC pages with this content. </div>

<div id="opacheader_notes" class="hint customization_note"> Include this content in the header of all pages in the OPAC. </div>

<div id="OpacLibraryInfo_notes" class="hint customization_note"> Include this content on the library information page in the OPAC. </div>

<div id="OpacLoginInstructions_notes" class="hint customization_note"> Show this content on the OPAC login form when a patron is not logged in. </div>

<div id="OpacMaintenanceNotice_notes" class="hint customization_note"> Show this content on the OPAC when the OpacMaintenance system preference is enabled. </div>

<div id="OpacMainUserBlock_notes" class="hint customization_note"> Show this content in its own column on the main page of the OPAC. </div>

<div id="OpacMoreSearches_notes" class="hint customization_note"> Add additional elements to the navigation bar below the simple search form. </div>

<div id="OpacMySummaryNote_notes" class="hint customization_note"> Note to display on the patron summary page. This note only appears if the patron is logged in. </div>

<div id="OpacNav_notes" class="hint customization_note"> Show this content on the left hand column of the main page and patron account on the OPAC (generally navigation links). </div>

<div id="OpacNavBottom_notes" class="hint customization_note"> Show this content on the left hand column of the main page and patron account on the OPAC, after OpacNav, and before patron account links if available. </div>

<div id="OpacNavRight_notes" class="hint customization_note"> Show this content in the right hand column of the main page under the main login form. </div>

<div id="OPACResultsSidebar_notes" class="hint customization_note"> Show this content under the facets in OPAC search results. </div>

<div id="OpacSuggestionInstructions_notes" class="hint customization_note"> Show this content at the top of the purchase suggestion form in the OPAC. </div>

<div id="OpacSuppressionMessage_notes" class="hint customization_note">
    Display the following message on the redirect page for suppressed bibliographic records. Depends on the system preferences OpacSuppression and OpacSuppressionRedirect.
</div>

<div id="PatronSelfRegistrationAdditionalInstructions_notes" class="hint customization_note"> Show the following content on the patron self-registration confirmation page. </div>

<div id="RoutingListNote" class="hint customization_note"> Include the following note on all routing list slips. </div>

<div id="SCOMainUserBlock_notes" class="hint customization_note"> Show this content on the web-based self checkout screen. </div>

<div id="SelfCheckHelpMessage_notes" class="hint customization_note"> Show this content on the Help page of the web-based self checkout system. </div>

<div id="SelfCheckInMainUserBlock_notes" class="hint customization_note"> Show this content on the self check-in screen. </div>

<div id="StaffAcquisitionsHome_notes" class="hint customization_note"> Show this content on the acquisitions home page in the staff interface. </div>

<div id="StaffAuthoritiesHome_notes" class="hint customization_note"> Show this content on the authorities home page in the staff interface. </div>

<div id="StaffCataloguingHome_notes" class="hint customization_note"> Show this content on the cataloging home page in the staff interface. </div>

<div id="StaffListsHome_notes" class="hint customization_note"> Show this content on the lists home page in the staff interface. </div>

<div id="StaffLoginInstructions_notes" class="hint customization_note"> Show this content on the staff interface login page. </div>

<div id="StaffPatronsHome_notes" class="hint customization_note"> Show this content on the patrons home page in the staff interface. </div>

<div id="StaffPOSHome_notes" class="hint customization_note"> Show this content on the point of sale home page in the staff interface. </div>

<div id="StaffSerialsHome_notes" class="hint customization_note"> Show this content on the serials home page in the staff interface. </div>
