<!-- ill-batch-table-strings.inc -->
<script>
    var ill_batch_borrower_details = _("View borrower details");
    var ill_batch_edit = _("Edit");
    var ill_batch_delete = _("Delete");
    var ill_batch_confirm_delete = _("Are you sure you want to delete this batch? All attached requests will be detached.");
    var ill_batch_delete_fail = _("Unable to delete batch");
</script>
<!-- / ill-batch-table-strings.inc -->
