<div>
    <div>[% service.name %]</div>
    <table class="ill-availability" id="[% service.id %]">
        <thead id="[% service.id %]-header">
            <tr>
                <th>Source</th>
                <th>Title</th>
                <th>Author</th>
                <th>ISBN</th>
                <th>ISSN</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody id="[% service.id %]-body">
        </tbody>
    </table>
</div>
