<!-- ill-list-table-strings.inc -->
<script>
    var ill_borrower_details = _("View patron details");
    var ill_manage = _("Manage request");
    var ill_manage_select_backend_first = _("Select a backend first");
    var ill_all_status_aliases = _("All status aliases");
    var ill_no_status_alias = _("No status alias");
    var ill_status_aliases = _("Status aliases");
</script>
<!-- / ill-list-table-strings.inc -->
