<!-- ill-list-table-strings.inc -->
<script>
    var ill_borrower_details = _("View patron details");
    var ill_biblio_details = _("View bibliographic record");
    var ill_statuses = {
        new: _("New request"),
        req: _("Requested"),
        genreq: _("Requested from partners"),
        rev: _("Reverted"),
        que: _("Queued request"),
        canc: _("Cancellation requested"),
        comp: _("Completed"),
        del: _("Delete request")
    };
    var ill_manage = _("Manage request");
    var ill_columns = {
        biblio_id: _("Bibliographic record ID"),
        updated: _("Updated on")
    };
</script>
<!-- / ill-list-table-strings.inc -->
