<div>
    <table class="ill-availability" id="[% service.id | html %]">
        <thead id="[% service.id | html %]-header">
            <tr>
                <th>Source</th>
                <th>Title</th>
                <th>Author</th>
                <th>ISBN</th>
                <th>ISSN</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody id="[% service.id | html %]-body"> </tbody>
    </table>
</div>
