<script type="text/javascript">
    var MSG_LETTERS_ONLY=(_("Please only enter letters."));
    var MSG_PASSWORD_MISMATCH=(_("The entered passwords do not match"));
    var MSG_ONE_ENROLLMENTPERIOD =(_("Please choose an enrollment period in months OR by date."));
    var MSG_ONLY_ONE_ENROLLMENTPERIOD=(_("Please only choose one enrollment period."));
    var MSG_LETTERS_NUMBERS_ONLY=(_("Please only enter letters or numbers."));
</script>
