<ul>
	<li><a href="/cgi-bin/koha/labels/label-home.pl">Layouts</a></li>
	<li><a href="/cgi-bin/koha/labels/label-templates.pl">Templates</a></li>
	<li><a href="/cgi-bin/koha/labels/label-profiles.pl">Printer Profiles</a></li>
	<li><a href="/cgi-bin/koha/labels/label-manager.pl?type=labels">Create or Print Label Batches</a></li>
	<li><a href="/cgi-bin/koha/labels/label-manager.pl?type=patroncards">Create or Print Patron Card Batches</a></li>
</ul>
