<div id="navmenu"><ul id="navmenulist">
	<li><a href="/cgi-bin/koha/labels/label-home.pl">Labels Home</a></li>
	<li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=layout">Manage Layouts</a></li>
	<li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=template">Manage Templates</a></li>
	<li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=profile">Manage Profiles</a></li>
	<li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=batch">Manage Batches</a></li>
</ul>
</div>
