<div id="toolbar" class="btn-toolbar">
    <div class="btn-group">
        <button class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-plus"></i> New</button>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-batch.pl?op=new">Label batch</a></li>
            <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-layout.pl?op=new">Label layout</a></li>
            <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-template.pl?op=new">Label template</a></li>
            <li><a class="dropdown-item" href="/cgi-bin/koha/labels/label-edit-profile.pl?op=new">Printer profile</a></li>
        </ul>
    </div>
</div>
