<div id="submenu">
    <p>
<ul>
	<li>        <a href="/cgi-bin/koha/admin/branches.pl">Libraries</a></li>
	<li>        <a href="/cgi-bin/koha/admin/aqbookfund.pl">Funds</a></li>
	<li>        <a href="/cgi-bin/koha/admin/itemtypes.pl">Item types</a></li>
	<li>        <a href="/cgi-bin/koha/admin/categorie.pl">Patron types and categories</a></li>
	<li>        <a href="/cgi-bin/koha/admin/issuingrules.pl">Issuing rules</a></li>
</ul>
    </p>
    <p>
<ul>
	<li>        <a href="/cgi-bin/koha/admin/biblio_framework.pl">Biblio Framework</a></li>
	<li>        <a href="/cgi-bin/koha/admin/authtypes.pl">Thesaurus Framework</a></li>
	<li>        <a href="/cgi-bin/koha/admin/authorised_values.pl">Authorised values</a></li>
</ul>
    </p>
</div>
