<div id="submenu">
    <a href="/cgi-bin/koha/catalogue/search.pl?type=intranet">Search</a>
    <a href="/cgi-bin/koha/cataloguing/addbooks.pl">Cataloguing</a>
    <a href="/cgi-bin/koha/cataloguing/addbiblio.pl">Add MARC record</a>
    <a class="submenu serial" href="/cgi-bin/koha/serials/serials-home.pl">Subscriptions</a>
    <a href="/cgi-bin/koha/bookshelves/shelves.pl">Virtual shelves</a>
    <a href="/cgi-bin/koha/reviews/reviewswaiting.pl">Manage reviews</a>
</div>

<div id="main">
