<div id="submenu">
    <a href="/cgi-bin/koha/circ/selectbranchprinter.pl">Set library</a>
    <a href="/cgi-bin/koha/circ/pendingreserves.pl" title="holds to retrieve off the shelf">Holds to pull</a>
    <a href="/cgi-bin/koha/circ/waitingreserves.pl" title="holds waiting for patron pickup">Holds awaiting pickup</a>
    <a href="/cgi-bin/koha/circ/transferstodo.pl" title="transfers to do from your library">Transfers to do</a>
    <a href="/cgi-bin/koha/circ/transferstoreceive.pl" title="transfers to receive at your library">Transfers to receive</a>
    <a href="/cgi-bin/koha/circ/overdue.pl">Overdues</a>
    <a href="/cgi-bin/koha/circ/branchoverdues.pl">Fines</a>
    <a href="/cgi-bin/koha/circ/stats.pl?time=yesterday">Daily reconciliation</a>
</div>

<div id="main">
