<div id="submenu">
    <a href="/cgi-bin/koha/tools/tools-home.pl">Tools Home</a>
    <a href="/cgi-bin/koha/tools/holidays.pl">Holidays</a>
    <a href="/cgi-bin/koha/tools/koha-news.pl">News</a>
    <a href="/cgi-bin/koha/tools/inventory.pl">Inventory/stocktaking</a>
    <a href="/cgi-bin/koha/tools/cleanborrowers.pl">Clean borrowers</a>
    <a href="/cgi-bin/koha/tools/itemslost.pl">Items lost</a>
    <a href="/cgi-bin/koha/tools/export.pl">Export</a>
    <a href="/cgi-bin/koha/tools/import.pl">Import</a>
    <a href="/cgi-bin/koha/tools/letter.pl">Letters</a>
    <a href="/cgi-bin/koha/tools/breeding.pl">Reservoir</a>
    <a href="/cgi-bin/koha/labels/labels-home.pl">Labels</a>
    <a href="/cgi-bin/koha/tools/overduerules.pl">overdue rules</a>
    <a href="/cgi-bin/koha/tools/viewlog.pl">Log viewer</a>
</div>

<div id="main">
