<div id="submenu">
    <ul>
    <li>
    <a href="/cgi-bin/koha/circ/circulation.pl">Issues</a>
    <a href="/cgi-bin/koha/circ/returns.pl">Returns</a>
    <a href="/cgi-bin/koha/circ/branchtransfers.pl">Transfers</a>
    <a href="/cgi-bin/koha/circ/selectbranchprinter.pl">Set branch</a>
    </li>
    <li>
    Reserves <a href="/cgi-bin/koha/circ/reserve.pl">Pending</a>
    <a href="/cgi-bin/koha/circ/branchreserves.pl">Waiting</a>
    Transfers <a href="/cgi-bin/koha/circ/waitingreservestransfers.pl">to do</a>
    <a href="/cgi-bin/koha/circ/currenttransfers.pl">to recieve</a>
    </li>
    <li>
	<a href="/cgi-bin/koha/circ/overdue.pl">Overdues</a>
    <a href="/cgi-bin/koha/circ/branchoverdues.pl">Overdues by branch/department</a>
    <a href="/cgi-bin/koha/circ/stats.pl?time=yesterday">Daily reconciliation</a>
    </li>
    </ul>
</div>

<div id="main">
