<div id="submenu">
<ul>
	<li>    <a href="/cgi-bin/koha/acqui/supplier.pl?op=enter">Add supplier</a></li>
	<li>    <a href="/cgi-bin/koha/acqui/lateorders.pl">Late orders</a></li>
	<li>    <a href="/cgi-bin/koha/acqui/histsearch.pl">History search</a></li>
	<li>    <a href="/cgi-bin/koha/suggestion/acceptorreject.pl?op=aorr_confirm">Manage suggestions</a></li>
	<li>    <a href="/cgi-bin/koha/admin/aqbookfund.pl">Parameters</a></li>
</ul>
</div>