<div id="submenu">
    <p>
        <a href="/cgi-bin/koha/admin/branches.pl">Libraries</a>
        <a href="/cgi-bin/koha/admin/aqbookfund.pl">Funds</a>
        <a href="/cgi-bin/koha/admin/itemtypes.pl">Item types</a>
        <a href="/cgi-bin/koha/admin/categorie.pl">Patron categories</a>
        <a href="/cgi-bin/koha/admin/issuingrules.pl">Issuing rules</a>
    </p>
    <p>
        <a href="/cgi-bin/koha/admin/biblio_framework.pl">Biblio Framework</a>
        <a href="/cgi-bin/koha/admin/authtypes.pl">Thesaurus Framework</a>
        <a href="/cgi-bin/koha/admin/authorised_values.pl">Authorised values</a>
    </p>
</div>

<div id="main">
