<p>
	<a href="/cgi-bin/koha/loadmodules.pl?module=search&amp;marc=1&amp;type=intranet">Search</a>
	<a href="/cgi-bin/koha/loadmodules.pl?module=addbiblio&amp;type=intranet">Add biblio</a>
	<a class="submenu bull" href="/cgi-bin/koha/serials/serials-home.pl">Subscriptions</a>
	<a href="/cgi-bin/koha/serials/lateissues.pl">Late issues</a>
	<a href="/cgi-bin/koha/bookshelves/shelves.pl">Virtual shelves</a>
</p>