<div id="submenu">
 	<a href="/cgi-bin/koha/members/members-home.pl">Search</a>
 	<a href="/cgi-bin/koha/members/memberentry.pl?op=add&category_type=A"/>Add adult</a>
 	<a href="/cgi-bin/koha/members/memberentry.pl?op=add&category_type=C"/>Add child</a>
 	<a href="/cgi-bin/koha/members/memberentry.pl?op=add&category_type=P"/>Add prof</a>
 	<a href="/cgi-bin/koha/members/memberentry.pl?op=add&category_type=I"/>Add org</a>
</div>