<div id="submenu">
    <a href="/cgi-bin/koha/acqui/supplier.pl?op=enter">Add supplier</a>
    <a href="/cgi-bin/koha/acqui/lateorders.pl">Late orders</a>
    <a href="/cgi-bin/koha/acqui/histsearch.pl">History search</a>
    <a href="/cgi-bin/koha/suggestion/acceptorreject.pl?op=aorr_confirm">Manage suggestions</a>
    <a href="/cgi-bin/koha/admin/aqbookfund.pl">Parameters</a>
</div>

<div id="main">
