<div id="submenu">
    <p>
        <a href="/cgi-bin/koha/admin/systempreferences.pl">System pref</a>
        <a href="/cgi-bin/koha/admin/branches.pl">Branches</a>
        <a href="/cgi-bin/koha/admin/aqbookfund.pl">Funds</a>
        <a href="/cgi-bin/koha/admin/currency.pl">Currencies</a>
    </p>
    <p>
        <a href="/cgi-bin/koha/admin/itemtypes.pl">Item types</a>
        <a href="/cgi-bin/koha/admin/categorie.pl">Borrower categories</a>
        <a href="/cgi-bin/koha/admin/issuingrules.pl">Issuing rules</a>
        <a href="/cgi-bin/koha/admin/z3950servers.pl">Z39.50 Servers</a>
    </p>
    <p>
        <a href="/cgi-bin/koha/admin/biblio_framework.pl">Biblio Framework</a>
        <a href="/cgi-bin/koha/admin/authtypes.pl">Thesaurus Framework</a>
        <a href="/cgi-bin/koha/admin/authorised_values.pl">Authorised values</a>
        <a href="/cgi-bin/koha/admin/koha2marclinks.pl">Links Koha-MARC DB</a>
        <a href="/cgi-bin/koha/admin/checkmarc.pl">MARC Check</a>
    </p>
</div>

<div id="main">
