<div id="submenu">
 	<a href="/cgi-bin/koha/members/members-home.pl">Borrowers</a>
 	<a href="/cgi-bin/koha/members/memberentry.pl?op=add&amp;category_type=A">Add adult</a>
 	<a href="/cgi-bin/koha/members/memberentry.pl?op=add&amp;category_type=C">Add child</a>
 	<a href="/cgi-bin/koha/members/memberentry.pl?op=add&amp;category_type=P">Add professional</a>
 	<a href="/cgi-bin/koha/members/memberentry.pl?op=add&amp;category_type=I">Add organisation</a>
</div>

<div id="main">
