[%# transletable strings for merge-record.js %]
<script type="text/javascript">
    var MSG_MERGEREC_ALREADY_EXISTS = _("The field is non-repeatable and already exists in the destination record. Therefore, you cannot add it.");
    var MSG_MERGEREC_SUBFIELD_PRE   = _("This subfield cannot be added: there is no");
    var MSG_MERGEREC_SUBFIELD_POST  = _("field in the destination record.");
</script>