<div id="return-claims">
  <table id="return-claims-table" class="table table-bordered table-striped">
      <thead>
          <tr>
              <th class="return-claim-id">Claim ID</th>
              <th class="return-claim-record-title anti-the">Title</th>
              <th class="return-claim-notes">Notes</th>
              <th class="return-claim-created-on">Created on</th>
              <th class="return-claim-updated-on">Updated on</th>
              <th class="return-claim-resolution">Resolution</th>
              <th class="return-claim-actions">&nbsp;</th>
          </tr>
      </thead>
  </table>
</div>
