<div id="toolbar" class="btn-toolbar">
    <a class="btn btn-small" id="layouts" href="/cgi-bin/koha/patroncards/edit-layout.pl?op=new">New layout</a>
    <a class="btn btn-small" id="templates" href="/cgi-bin/koha/patroncards/edit-template.pl?op=new">New template</a>
    <a class="btn btn-small" id="profiles" href="/cgi-bin/koha/patroncards/edit-profile.pl?op=new">New profile</a>
    <a class="btn btn-small" id="batches" href="/cgi-bin/koha/patroncards/edit-batch.pl?op=new">New batch</a>
</div>
