<div id="toolbar" class="btn-toolbar">
    <div class="btn-group">
        <button class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-plus"></i> New</button>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/edit-batch.pl?op=new">Card batch</a></li>
            <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/image-manage.pl">Image</a></li>
            <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/edit-layout.pl?op=new">Layout</a></li>
            <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/edit-template.pl?op=new">Card template</a></li>
            <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/edit-profile.pl?op=new">Printer profile</a></li>
        </ul>
    </div>
    <div class="btn-group">
        <button class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa-solid fa-pencil" aria-hidden="true"></i> Manage</button>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/manage.pl?card_element=batch">Card batches</a></li>
            <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/image-manage.pl">Images</a></li>
            <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/manage.pl?card_element=layout">Layouts</a></li>
            <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/manage.pl?card_element=template">Card templates</a></li>
            <li><a class="dropdown-item" href="/cgi-bin/koha/patroncards/manage.pl?card_element=profile">Printer profiles</a></li>
        </ul>
    </div>
</div>
