<div id="navmenu"><ul id="navmenulist">
    <li><a href="/cgi-bin/koha/patroncards/home.pl">Patron card creator home</a></li>
    <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=layout">Manage layouts</a></li>
    <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=template">Manage templates</a></li>
    <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=profile">Manage profiles</a></li>
    <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=batch">Manage batches</a></li>
    <li><a href="/cgi-bin/koha/patroncards/image-manage.pl">Manage images</a></li>
</ul>
</div>
