<!-- Begin Preservation Resident Search Box -->

<div id="header_search">
    <div id="preservation_search" class="residentsearch">
        <form name="find_stuff" action="/cgi-bin/koha/preservation/home.pl" method="get">
            <span class="form-title">
                <label class="control-label">Preservation search</label>
            </span>

            <span class="form-content">
                <input type="text" name="supplier" id="preservation_search_input" class="head-searchbox form-control" placeholder="Search preservation" />
            </span>
            <button type="submit"><i class="fa fa-arrow-right"></i></button>
        </form>
    </div>

    <ul>
        <li
            ><a title="Preservation search" href="#preservation_search"><i class="fa fa-upload"></i> <span class="tab-title">Preservation search</span></a></li
        >
    </ul> </div
><!-- /header_search -->

<!-- End Main page Resident Search Box -->
