<div id="toolbar" class="btn-toolbar">
        <div class="btn-group"><a class="btn btn-small" id="add_quote" href="#"><i class="fa fa-plus"></i> Add quote</a></div>
        <div class="btn-group"><a class="btn btn-small" id="delete_quote" href="#"><i class="fa fa-trash"></i> Delete quote(s)</a></div>
        <div class="btn-group"><a class="btn btn-small" id="import_quotes" href="/cgi-bin/koha/tools/quotes-upload.pl"><i class="fa fa-folder-open"></i> Import quotes</a></div>
</div>
