<script type="text/javascript">
//<![CDATA[
    var CIRCULATION_RETURNED = _("Returned");
    var CIRCULATION_NOT_RETURNED = _("Unable to return");
    var CIRCULATION_RENEWED_DUE = _("Renewed, due:");
    var CIRCULATION_RENEW_FAILED = _("Renew failed:")
    var NOT_CHECKED_OUT = _("not checked out");
    var TOO_MANY_RENEWALS = _("too many renewals");
    var ON_RESERVE = _("on reserve");
    var REASON_UNKNOWN = _("reason unkown");
    var TODAYS_CHECKOUTS = _("Today's checkouts");
    var PREVIOUS_CHECKOUTS = _("Previous checkouts");
    var BY = _("by _AUTHOR_");
    var ON_HOLD = _("On hold");
    var NOT_RENEWABLE = _("Not renewable");
    var NOT_RENEWABLE_TOO_SOON = _("No renewal before %s");
    var NOT_RENEWABLE_AUTO_TOO_SOON = _("Scheduled for automatic renewal");
    var NOT_RENEWABLE_AUTO_RENEW = _("Scheduled for automatic renewal");
    var RENEWALS_REMAINING = _("%s of %s renewals remaining");
    var HOLD_IS_SUSPENDED = _("Hold is <strong>suspended</strong>");
    var UNTIL = _("until %s");
    var ITEM_IS_WAITING = _("Item is <strong>waiting</strong>"); //
    var AT = _("at %s");
    var ITEM_IS_IN_TRANSIT = _("Item is <strong>in transit</strong> from %s");
    var FROM = _("from");
    var NOT_TRANSFERRED_YET = _("Item hasn't been transferred yet from %s");
    var NO = _("No");
    var YES = _("Yes");
//]]>
</script>
