<script type="text/javascript">
//<![CDATA[
    var CIRCULATION_RETURNED = _("Returned");
    var CIRCULATION_NOT_RETURNED = _("Unable to return");
    var CIRCULATION_RENEWED_DUE = _("Renewed, due:");
    var CIRCULATION_RENEW_FAILED = _("Renew failed:")
    var NOT_CHECKED_OUT = _("not checked out");
    var TOO_MANY_RENEWALS = _("too many renewals");
    var ON_RESERVE = _("on reserve");
    var REASON_UNKNOWN = _("reason unkown");
    var TODAYS_CHECKOUTS = _("Today's checkouts");
    var PREVIOUS_CHECKOUTS = _("Previous checkouts");
    var BY = _("by");
    var ON_HOLD = _("On hold");
    var NOT_RENEWABLE = _("Not renewable");
    var OF = _("of");
    var RENEWALS_REMAINING = _("renewals remaining");
    var HOLD_IS = _("Hold is");
    var SUSPENDED = _("suspended");
    var UNTIL = _("until");
    var ITEM_IS = _("Item is");
    var WAITING = _("waiting");
    var AT = _("at");
    var IN_TRANSIT = _("in transit");
    var FROM = _("from");
    var NOT_TRANSFERRED_YET = _("Item hasn't been transferred yet from");
    var NO = _("No");
    var YES = _("Yes");
//]]>
</script>
