<div id="yui-b">
<!-- SUBTYPE LIMITS -->
		<fieldset>
		<legend>Coded Fields</legend>
		<p>
		<label>Audience</label>
		<select name="limit" class="subtype">
            <option value="" SELECTED="selected" >Any</option>
			<option value="aud:a">juvenile, general</option>
			<option value="aud:b">pre-primary (0-5)</option>
			<option value="aud:c">Primary (5-8)</option>
			<option value="aud:d">children (9-14)</option>
			<option value="aud:e">Young Adult</option>
			<option value="aud:k">Adult, serious</option>
			<option value="aud:m">Adult, General</option>
			<option value="aud:u">Unknown</option>
		</select>
		</p>
		<p>
		<label>Print</label>
        <select name="limit" class="subtype">
			<option value="" selected="selected" >any</option>
				<option value="Material-type:r">regular print</option>
				<option value="Material-type:d">large print</option>
				<option value="Material-type:e">newspaper format</option>
				<option value="Material-type:f">Braille or Moon script</option>
				<option value="Material-type:g">microprint</option>
				<option value="Material-type:h">hand-written</option>
				<option value="Material-type:i">multimedia</option>
				<option value="Material-type:j">mini-print</option>
				<option value="Material-type:z">other form of textual material</option>
		</select>
		</p>
		<p>
		<label>Feschrift Ind.</label>
		<select name="limit" class="subtype">
			<option value="" selected="selected" >Any</option>
            <option value="Literature-Code:a">fiction</option>
            <option value="Literature-Code:b">drama</option>
            <option value="Literature-Code:c">essays</option>
            <option value="Literature-Code:d">humour, satire</option>
            <option value="Literature-Code:e">letters</option>
            <option value="Literature-Code:f">short stories</option>
            <option value="Literature-Code:g">poetry</option>
            <option value="Literature-Code:h">speeches, oratory</option>
            <option value="Literature-Code:y">not a literary text</option>
            <option value="Literature-Code:z">multiple/other lit. forms</option>
		</select>
		</p>
        <p>
		<label>Biography</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Any</option>
            <option value="Biography-code:y">Not a biography</option>
            <option value="Biography-code:a">autobiography</option>
            <option value="Biography-code:b">individual biography</option>
            <option value="Biography-code:c">collective biography</option>
            <option value="Biography-code:d">contains biogr. data</option>
		</select>
        </p>
        <p>
		<label>Illustration</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Tout type d'illustration</option>
            <option value="Illustration-Code:a">Illustrations</option>
            <option value="Illustration-Code:b">Cartes</option>
            <option value="Illustration-Code:c">Portraits</option>
            <option value="Illustration-Code:d">cartes marines</option>
            <option value="Illustration-Code:e">plans</option>
            <option value="Illustration-Code:f">Planches</option>
            <option value="Illustration-Code:g">Musique imprimee</option>
            <option value="Illustration-Code:h">fac-similes</option>
            <option value="Illustration-Code:i">armoiries</option>
            <option value="Illustration-Code:j">Tables Genealogique</option>
            <option value="Illustration-Code:k">Formulaires</option>
            <option value="Illustration-Code:l">Specimens</option>
            <option value="Illustration-Code:m">Enregistrement sonore</option>
            <option value="Illustration-Code:n">Transparents</option>
            <option value="Illustration-Code:o">Enluminures</option>
            <option value="Illustration-Code:y">Sans illustrations</option>
        </select>
        </p>
		<p>
		<label>Content</label>
		<select name="limit" class="subtype">
			<option value="" >Any</option>
            <option value="ctype:a" >bibliography</option>
            <option value="ctype:b" >catalogue</option>
            <option value="ctype:c" >index</option>
            <option value="ctype:d" >abstract</option>
            <option value="ctype:e" >dictionary</option>
            <option value="ctype:f" >encyclopaedia</option>
            <option value="ctype:g" >directory</option>
            <option value="ctype:h" >project description</option>
            <option value="ctype:i" >statistics</option>
            <option value="ctype:j" >programmed text books</option>
            <option value="ctype:k" >patent</option>
            <option value="ctype:l" >standard</option>
            <option value="ctype:m" >dissertation or thesis</option>
            <option value="ctype:n" >laws and legislation</option>
            <option value="ctype:o" >numeric table</option>
            <option value="ctype:p" >technical report</option>
            <option value="ctype:q" >examination paper</option>
            <option value="ctype:r" >literature surveys/reviews</option>
            <option value="ctype:s" >treaties</option>
            <option value="ctype:t" >cartoons or comic strips</option>
            <option value="ctype:z" >other</option>
		</select>
        </p>
        <p>
		<label>Type vid&eacute;o</label>
		<select name="limit" class="subtype">
            <option value="">Tout type video</option>
			<option value="Video-mt:a">Film</option>
			<option value="Video-mt:b">Document &agrave; projeter</option>
			<option value="Video-mt:c">Enregistrement video</option>
		</select>
        </p>
		</fieldset>
		<fieldset>
		<legend>P&eacute;riodique</legend><p>
		<p>
		<label>Type periodique</label>
		<select name="limit" class="subtype">
           <option value="">Tout type de periodique</option>
           <option value="Type-Of-Serial:a">Periodique</option>
			<option value="Type-Of-Serial:b">Collection des monographies</option>
			<option value="Type-Of-Serial:c">Journal</option>
			<option value="Type-Of-Serial:z">autres</option>
		</select>
		</p>
		<p>
		<label>P&eacute;riodicit&eacute;</label>
		<select name="limit" class="subtype">
			<option value="">Toute P&eacute;riodicit&eacute;</option>
				<option value="Frequency-code:a">Quotidien</option>
				<option value="Frequency-code:b">Bihebdomadaire</option>
				<option value="Frequency-code:c">Hebdomadaire</option>
				<option value="Frequency-code:d">Toutes les deux semaines</option>
				<option value="Frequency-code:e">Deux fois par mois</option>
				<option value="Frequency-code:f">Mensuel</option>
				<option value="Frequency-code:g">Bimestriel</option>
				<option value="Frequency-code:h">Trimestriel</option>
				<option value="Frequency-code:i">Trois fois par an</option>
				<option value="Frequency-code:j">Semestriel</option>
				<option value="Frequency-code:k">Annuel</option>
				<option value="Frequency-code:l">Bisanuel</option>
				<option value="Frequency-code:m">Triennal</option>
				<option value="Frequency-code:n">Trois fois par semaine</option>
				<option value="Frequency-code:o">Trois fois par mois</option>
				<option value="Frequency-code:u">Inconnue</option>
				<option value="Frequency-code:y">Sans periodicite</option>
				<option value="Frequency-code:i">Autre</option>
		</select>
		</p>
		<p>
		<label>Toute R&eacute;gularit&eacute;</label>
		<select name="limit" class="subtype">
            <option value="">R&eacute;gularit&eacute;</option>
				<option value="Regularity-code:u">Inconnu</option>
				<option value="Regularity-code:a">Regulier</option>
				<option value="Regularity-code:b">Normalement irregulier</option>
				<option value="Regularity-code:y">Irregulier</option>
		</select>
        </p>

        </fieldset>
		<fieldset>
		<legend>Document pictural</legend><p>
		<select name="limit" class="subtype">
				<option value="">Tout type</option>
				<option value="Graphics-type:a">Collage</option>
				<option value="Graphics-type:b">Dessin</option>
				<option value="Graphics-type:c">Peinture</option>
				<option value="Graphics-type:d">Reproduction photomecanique</option>
				<option value="Graphics-type:e">Negatif photo</option>
				<option value="Graphics-type:f">Tirage photographique</option>
				<option value="Graphics-type:h">Image</option>
				<option value="Graphics-type:i">Gravure</option>
				<option value="Graphics-type:k">Dessin technique</option>
				<option value="Graphics-type:z">Autres types de documents graphique non projetable</option>
		</select>
		<select name="limit" class="subtype">
            <option value="">tout support</option>
            <option value="Graphics-support:a">Toile</option>
            <option value="Graphics-support:b">Carte bristol</option>
            <option value="Graphics-support:c">Carton / carte a dessin</option>
            <option value="Graphics-support:d">Verre</option>
            <option value="Graphics-support:j">Platre</option>
            <option value="Graphics-support:k">Isorel</option>
            <option value="Graphics-support:l">Porcelaine</option>
            <option value="Graphics-support:m">Pierre</option>
            <option value="Graphics-support:n">Bois</option>
            <option value="Graphics-support:u">Inconnu</option>
            <option value="Graphics-support:v">Support composite</option>
            <option value="Graphics-support:e">Synthetique (plastique, vinyle...)</option>
            <option value="Graphics-support:f">Peau</option>
            <option value="Graphics-support:g">Textile</option>
            <option value="Graphics-support:h">Metal</option>
            <option value="Graphics-support:i">Papier</option>
            <option value="Graphics-support:z">Autres</option>
		</select>
        </p>

</fieldset>
</div>
