<div id="menu">
<ul>
    
    <li <!-- TMPL_IF NAME="Admin" -->class="active" <!-- /TMPL_IF -->><a title="Administration" href="/cgi-bin/koha/admin/systempreferences.pl?tab=Admin">Admin</a></li>
    <li <!-- TMPL_IF NAME="Acquisitions" -->class="active" <!-- /TMPL_IF -->><a title="Acquisitions" href="/cgi-bin/koha/admin/systempreferences.pl?tab=Acquisitions">Acquisitions</a></li>
    <li <!-- TMPL_IF NAME="Authorities" -->class="active" <!-- /TMPL_IF -->><a title="Authority Control" href="/cgi-bin/koha/admin/systempreferences.pl?tab=Authorities">Authorities</a></li>
    <li <!-- TMPL_IF NAME="Cataloguing" -->class="active" <!-- /TMPL_IF -->><a title="Cataloging" href="/cgi-bin/koha/admin/systempreferences.pl?tab=Cataloguing">Cataloguing</a></li>
    <li <!-- TMPL_IF NAME="Circulation" -->class="active" <!-- /TMPL_IF -->><a title="Circulation" href="/cgi-bin/koha/admin/systempreferences.pl?tab=Circulation">Circulation</a></li>
    <li <!-- TMPL_IF NAME="FRBR" -->class="active" <!-- /TMPL_IF -->><a title="Functional Requiremnets for Bibliographic Records" href="/cgi-bin/koha/admin/systempreferences.pl?tab=FRBR">FRBR</a></li>
    <li <!-- TMPL_IF NAME="I18N/L10N" -->class="active" <!-- /TMPL_IF -->><a title="Internationalization and Localization" href="/cgi-bin/koha/admin/systempreferences.pl?tab=I18N/L10N">I18N/L10N</a></li>
    <li <!-- TMPL_IF NAME="LOGFeatures" -->class="active" <!-- /TMPL_IF -->><a title="Transaction Logs" href="/cgi-bin/koha/admin/systempreferences.pl?tab=LOGFeatures">Logs</a></li>
    <li <!-- TMPL_IF NAME="OPAC" -->class="active" <!-- /TMPL_IF -->><a title="Online Public Access Catalog" href="/cgi-bin/koha/admin/systempreferences.pl?tab=OPAC">OPAC</a></li>
    <li <!-- TMPL_IF NAME="OPACFeatures" -->class="active" <!-- /TMPL_IF -->><a title="OPAC Features" href="/cgi-bin/koha/admin/systempreferences.pl?tab=OPACFeatures">OPAC Features</a></li>
    <li <!-- TMPL_IF NAME="Patrons" -->class="active" <!-- /TMPL_IF -->><a title="Patrons" href="/cgi-bin/koha/admin/systempreferences.pl?tab=Patrons">Patrons</a></li>
    <li <!-- TMPL_IF NAME="Searching" -->class="active" <!-- /TMPL_IF -->><a title="Searching" href="/cgi-bin/koha/admin/systempreferences.pl?tab=Searching">Searching</a></li>
    <li <!-- TMPL_IF NAME="StaffClient" -->class="active" <!-- /TMPL_IF -->><a title="Staff Client" href="/cgi-bin/koha/admin/systempreferences.pl?tab=StaffClient">Staff Client</a></li>
    <li <!-- TMPL_IF NAME="" -->class="active" <!-- /TMPL_IF -->><a href="/cgi-bin/koha/admin/systempreferences.pl">Local Use</a></li>
</ul>
</div>
