<ul>
	<li><a href="/cgi-bin/koha/tools/tools-home.pl">Tools Home</a></li>
	<li><a href="/cgi-bin/koha/tools/holidays.pl">Holidays</a></li>
	<li><a href="/cgi-bin/koha/tools/koha-news.pl">News</a></li>
	<li><a href="/cgi-bin/koha/tools/inventory.pl">Inventory/stocktaking</a></li>
	<li><a href="/cgi-bin/koha/tools/cleanborrowers.pl">Clean borrowers</a></li>
	<li><a href="/cgi-bin/koha/tools/export.pl">Export</a></li>
	<li><a href="/cgi-bin/koha/tools/import.pl">Import</a></li>
	<li><a href="/cgi-bin/koha/tools/letter.pl">Notices</a></li>
	<li><a href="/cgi-bin/koha/tools/overduerules.pl">Notice/status triggers</a></li>
	<li><a href="/cgi-bin/koha/tools/import.pl">Reservoir</a></li>
	<li><a href="/cgi-bin/koha/labels/label-home.pl">Labels</a></li>
	<li><a href="/cgi-bin/koha/tools/viewlog.pl">Log viewer</a></li>
</ul>
